colorstackorg/oyster

CONTRIBUTING.md
This PR updates the name of the Git repository to clone from `colorstack.git` to `oyster.git`.
=> docs: update git repository name to clone ⬇️

CONTRIBUTING.md
Updates documentation on how to set up `.env` files.
=> docs: make `.env` setup clearer 🧠

CONTRIBUTING.md
This PR:
- Updates the path to the `core` package in documentation.
- Updates the command to create the `colorstack-test` database.
=> docs: fix path to `core` package for `.env` setup 🔨

CONTRIBUTING.md
Closes #15.
This PR:
- Adds links to GitHub articles on how to sync a forked repository.
=> docs: how to sync a forked repository 🔁

CONTRIBUTING.md
This PR adds a note about prioritizing ColorStack member contributions first.
=> docs: add note about ColorStack members ❤️

README.md
This PR adds _Oyster_ to the `README.md` title/description. Still have a long way to go in terms of branding, though.
=> docs: add oyster to the `README.md` 🦪

CONTRIBUTORS.yml
This PR initializes the `CONTRIBUTORS.yml` file, which all contributors can/should sign!
=> chore: initialize `CONTRIBUTORS.yml` file ✏️

CONTRIBUTORS.yml
Added my username to `CONTRIBUTORS.yml`.
=> chore: my first contribution ❤️

.github/ISSUE_TEMPLATE/general.md, CONTRIBUTORS.yml
Closes #35 
- Has added a template for general issues 
- New template can be found in the `.github/ISSUES_TEMPLATE` folder.
=> chore: add general issue template ❤️ 

apps/member-profile/app/routes/_profile.home.tsx
=> feat: add GitHub link as important resource 🏡

CONTRIBUTORS.yml
=> chore: my first contribution ✏️

CONTRIBUTORS.yml
Add myself to contributors doc :)
=> chore: add myself to contributors doc 😁

CONTRIBUTORS.yml
Add my github username to contributors list 👨🏽‍💻
=> chore: my first contribution 🚀 

.github/workflows/ci.yml, CONTRIBUTING.md, apps/admin-dashboard/.env.example, apps/api/.env.example, apps/member-profile/.env.example, package.json, packages/core/.env.example, packages/core/package.json, packages/core/src/infrastructure/database/scripts/setup.sql, packages/core/src/infrastructure/database/scripts/setup.ts, packages/core/vitest.config.ts
Closes #60.
Closes #61.
This PR:
- Implements a script to initialize the databases needed for development.
- Updates documentation to just run `yarn db:setup` instead of the `CREATE DATABASE` commands.
- Updates name of the test database to use snake_case.
- Updates `.env.example` files to include username/password.
- Updates the CI database's username/password similarly.
=> feat: implement database initialization script 📝

packages/core/src/infrastructure/database/scripts/setup.ts
Adds a database user and name to db:setup script to prevent errors on some versions of psql. Also fixes throwing errors on psql warnings that don't need to be thrown.
=> fix: add database user and name to prevent errors 🛠️

packages/core/src/modules/application/queries/list-applications.ts
Closes #33.
Updates order in which student applications are shown.
- change order from 'desc' to 'asc' (descending) (ascending)
=> fix: update order of applications ⚡

.github/ISSUE_TEMPLATE/config.yml
Updates the link for the "Ask a Question" option when creating an issue. It now includes a link to the `#oyster` channel.
=> chore: add channel id to slack link 🔗

packages/core/src/infrastructure/database/scripts/seed.ts, packages/core/src/infrastructure/database/shared/truncate.ts, packages/core/src/infrastructure/database/test/setup.ts
This PR:
- Makes `truncate` a shared database utility.
- Puts part of seed script in a transaction.
=> refactor: use truncate in `db:seed` script 🌱

apps/member-profile/app/entry.server.tsx, apps/member-profile/app/routes/_profile.census.tsx, apps/member-profile/app/routes/_profile.tsx, apps/member-profile/app/shared/constants.ts, apps/member-profile/vite.config.ts, packages/core/src/modules/feature-flag/feature-flag.shared.ts, packages/core/src/modules/survey/survey.types.ts, packages/core/src/modules/survey/use-cases/import-survey-responses.ts, packages/ui/src/components/dashboard.tsx, packages/utils/src/sleep.test.ts
Makes progress on #70.
This PR:
- Adds census page in Member Profile.
- Add feature flag to guard the census page.
=> feat: guard census page w/ feature flag ⛳️

docs/how-to-implement-a-database-migration.md, package.json, packages/db/package.json, packages/db/src/scripts/create-migration.ts, yarn.lock
- Implements script to generate boilerplate migration file (automatically has timestamp) and prompts user for migration name.
- Adds the `db:migration:create` command at the root.
- Updates documentation on "How to Create a Migration" file.
=> chore: add script to generate migration files 👨‍🍳

CONTRIBUTING.md, apps/admin-dashboard/app/routes/login.otp.verify.tsx, apps/member-profile/app/routes/_public.login.otp.verify.tsx, packages/core/src/modules/authentication/ui/one-time-code-form.tsx, packages/core/src/modules/authentication/use-cases/send-one-time-code.ts, packages/core/src/modules/authentication/use-cases/verify-one-time-code.ts, packages/core/src/shared/env.ts
This PR enables us to bypass authentication in the development environment.
=> feat: bypass authentication in dev environment 🔒

.github/workflows/ci.yml, packages/db/src/index.ts
This PR updates the CI pipeline to only run checks for workspaces that have changed in the PR.
=> chore: optimize turbo caching in ci 💧

packages/db/src/shared/utils.ts
=> fix: add `point` in kysely helper ☝️

apps/member-profile/app/routes/_profile.census.tsx
=> feat: add alumni fields to census form (3/x) 📝 

apps/member-profile/app/routes/_profile.census.tsx, apps/member-profile/app/shared/constants.ts, packages/core/src/member-profile.server.ts, packages/core/src/member-profile.ui.ts, packages/core/src/modules/census/census.types.ts, packages/core/src/modules/census/use-cases/submit-census-response.ts, packages/types/src/index.ts, packages/types/src/shared/zod.ts
=> feat: add cookie storage to census form 🍪

apps/member-profile/app/routes/_profile.census.tsx, packages/core/src/member-profile.ui.ts, packages/core/src/modules/census/census.types.ts, packages/core/src/modules/census/use-cases/submit-census-response.ts, packages/core/src/modules/member/use-cases/change-primary-email.ts, packages/db/src/migrations/20240412112539_census.ts, packages/types/src/domain/student.ts, packages/types/src/index.ts, packages/types/src/shared/zod.ts
=> feat: use case to submit census response 🦾

apps/member-profile/app/routes/_profile.points.tsx, packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/census/use-cases/submit-census-response.ts, packages/core/src/modules/gamification/use-cases/grant-gamification-points.ts, packages/db/src/migrations/20240412142933_census_gamification.ts, packages/types/src/domain/gamification.ts
=> feat: add gamification for submitting census response 🥇

CONTRIBUTORS.yml
Added my name to CONTRIBUTORS.yml
=> chore: my first contribution 🚀

apps/admin-dashboard/tailwind.config.js, apps/member-profile/app/routes/_profile.census._index.tsx, apps/member-profile/tailwind.config.js, packages/core/src/member-profile.ui.ts, packages/core/src/modules/census/census.types.ts, packages/core/src/modules/census/use-cases/submit-census-response.ts, packages/core/src/modules/employment/ui/company-field.tsx, packages/core/src/modules/member/use-cases/change-primary-email.ts
=> feat: add company field support to census 💼

apps/member-profile/app/routes/_profile.census._index.tsx, packages/core/src/modules/census/census.types.ts
=> feat: add nps + other questions to census 💼 

apps/member-profile/app/routes/_profile.census._index.tsx
Submitting the census on Safari v17 was failing due to the way it handles `<input type="hidden" />`.
=> fix: buggy census submission on safari 🐞

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/general.md, CONTRIBUTING.md
Update the GitHub issue templates and related documentation to guide users to GitHub Discussions for new ideas.
=> chore: update github issue templates 🎵

apps/member-profile/app/routes/_profile.census._index.tsx
Removes the saving of values as the user progress through the census form.
=> fix: intermittent census submission issues on firefox 🦊

packages/core/src/infrastructure/redis.ts, packages/core/src/modules/swag-pack/swag-pack.service.ts, packages/core/src/modules/swag-pack/use-cases/claim-swag-pack.ts, packages/core/src/modules/swag-pack/use-cases/notify-swag-pack-inventory.ts, packages/types/src/domain/types.ts, packages/types/src/index.ts
Fixes issue with the ordering swag packs due to inventory running out of our old packs.
=> fix: update swag pack logic to single pack 🎁

.vscode/extensions.json
Closes #163 
- Adds `extensions.json` file with recommend extensions for editing within vscode in `.vscode` directory.
=> chore: add `extensions.json` file with recommended extensions ↔️

packages/core/src/modules/member/events/member-primary-email-changed.ts
This PR fixes a bug in which if a member tried to change their primary email before accepting their Slack invitation, it would not update their Slack account email. To fix this, we now query the Slack API to try find the Slack account by email, if it's not already linked to their ColorStack profile.
=> fix: allow members to change slack email before accepting invite 📫

CONTRIBUTORS.yml
* Added my name to CONTRIBUTORS.yml
=> chore: my first contribution 🔥

CONTRIBUTING.md
- Adds instructions on how to access the Postgres DB in a container.
- Adds instructions on how to take down docker containers.
=> docs: add container cleanup instructions 🧹

packages/types/src/domain/application.ts
This PR allows us to submit applications using `@colorstack.org` - which is helpful when creating member accounts for internal team members.
=> feat: allow `@colorstack.org` email in application 📧

CONTRIBUTORS.yml
Added name to `CONTRIBUTORS.yml`.
- [] I have manually tested my code (if applicable).
- [] I have added/updated any relevant documentation (if applicable).
=> chore: my first contribution ❤️ 

apps/member-profile/app/routes/_public.apply._index.tsx, apps/member-profile/app/routes/_public.apply.thank-you.tsx, packages/core/src/modules/application/ui/application-form.tsx
=> feat: update application copy ✏️

packages/core/src/modules/notification/use-cases/send-email.ts
Closes #220.
This PR adds support for attachments within emails, and also adds the appropriate attachment to the `student-attended-onboarding-email`.
=> feat: attach onboarding slideshow to post-onboarding email 🛝

packages/core/src/modules/airtable/use-cases/create-airtable-member-record.ts, packages/core/src/modules/airtable/use-cases/create-airtable-record.ts, packages/db/src/migrations/20240515155334_airtable_id.ts
=> feat: add `airtable_id` on member record and save on creation 💨

packages/core/src/modules/airtable/use-cases/create-airtable-member-record.ts
=> feat: send additional fields in airtable record creation ✏️

packages/core/src/modules/airtable/use-cases/create-airtable-member-record.ts
Fixes small issue with record creation in Airtable.
=> fix: ambiguous column issue upon airtable creation 👩🏽‍🔧

apps/admin-dashboard/app/routes/_dashboard.resume-books.create.tsx, apps/admin-dashboard/app/routes/_dashboard.resume-books.tsx, apps/admin-dashboard/app/routes/_dashboard.tsx, apps/admin-dashboard/app/shared/constants.ts, packages/core/src/member-profile.server.ts, packages/core/src/member-profile.ui.ts, packages/core/src/modules/feature-flag/feature-flag.types.ts, packages/core/src/modules/resume-book/resume-book.types.ts, packages/core/src/modules/resume-book/use-cases/create-resume-book.ts, packages/db/src/migrations/20240517171307_resume_books.ts
Makes progress on #240.
- Implements a migration to create the `resume_books` table.
- Implements the ability to create a resume book in the Admin Dashboard.
- Implements the ability to view all resume books in the Admin Dashboard.
=> feat: create resume books in admin dashboard 📚

CONTRIBUTORS.yml
Added name to `CONTRIBUTORS.yml`.
=> chore: my first contribution ❤️ :)

apps/member-profile/app/routes/_profile.resources.tsx
Adds the full date when a user hovers over the relative posted date of a resource.
=> feat: add expanded date upon resource date hover 📆

apps/member-profile/app/routes/api.tags.add.ts
This PR ensures that creating a resource tag passes through validation, particular trimming the whitespaces off of a tag name.
=> fix: trim resource tag `name` ✂️

.vscode/extensions.json
Adds `EditorConfig.EditorConfig` to the recommended VSCode extensions.
=> chore: add `EditorConfig` to recommend vscode extensions ↗️

apps/member-profile/app/routes/_profile.home.tsx, packages/email-templates/emails/application-accepted.tsx
This PR update the onboarding session booking link.
=> fix: update onboarding session booking link ❗️

apps/member-profile/app/routes/_profile.home.claim-swag-pack._index.tsx, packages/core/src/member-profile.server.ts
- Checks the swag pack inventory in the claim swag modal.
- If there is no inventory, it shows a message, otherwise it will show the form.
- Uses `defer` for the first time, showing a spinner while waiting for the inventory to come through.
=> feat: check swag pack inventory before showing form 🚀

apps/admin-dashboard/app/routes/_dashboard.admins.tsx, packages/core/src/modules/admin/queries/list-admins.ts
This PR adds an `isArchived` column to the `listAdmins` query, so we'll show that for admins who no longer have access.
=> fix: show archived status for removed admins ❗️

apps/admin-dashboard/app/routes/_dashboard.tsx
This PR allows scrolling in the Admin Dashboard.
=> fix: allow scroll in admin dashboard page ❗️

apps/admin-dashboard/app/routes/_dashboard.applications.$id.accept.tsx
This PR fixes an issue with the overlay of the modal for accepting an application.
=> fix: accept application modal overlay ❗️

apps/member-profile/app/routes/_profile.companies.tsx, apps/member-profile/app/routes/_profile.companies_.$id.tsx, apps/member-profile/app/shared/components/review-form.tsx, packages/core/src/modules/employment/employment.types.ts, packages/ui/src/components/textarea.tsx
- Fixes bug with location of past employees.
- Updates the empty state message for companies.
- Reduces minimum character count to 750 for a company review.
- Adds a minimum character counter to the `Textarea`.
=> fix: companies v1 fast-follows 💨

packages/core/src/modules/employment/queries/list-company-employees.ts, packages/core/src/modules/employment/queries/list-company-reviews.ts
This PR fixes a bug which doesn't sort reviews/employees on an individual company page.
=> fix: add sorting to company reviews/employees 🔽

packages/core/src/modules/employment/queries/list-companies.ts
This PR fixes a bug that shows companies with 0 past or present employees.
=> fix: only show companies with 1 or more employees ❗️

apps/member-profile/app/routes/_profile.recap.$date.announcements.tsx, apps/member-profile/app/routes/_profile.recap.$date.tsx, apps/member-profile/app/shared/components/resource.tsx, apps/member-profile/app/shared/components/slack-message.tsx, packages/core/src/modules/slack/queries/list-slack-messages.ts
Fixes:
- A styling regression with the resource component.
- Shows an author for all Slack messages, even if unknown.
- The fetching of announcement messages which should only be top-level messages.
=> fix: minor issues w/ "last week in colorstack" ❗️

apps/member-profile/app/root.tsx
Fixes a bug that fails when trying to show relative time for a date that is longer than 1 month ago.
=> fix: add support for relative time beyond 1 month ❗️

apps/member-profile/app/routes/_profile.recap.$date.tsx, apps/member-profile/app/shared/components/slack-message.tsx, packages/infrastructure/src/mixpanel.ts
This PR fixes a bug that doesn't open a slack message in a new tab.
=> fix: open slack message in new tab ❗️

CONTRIBUTORS.yml
- Added my GitHub username to the contributors document
=> chore: my first contribution 🤍

CONTRIBUTORS.yml
- Added Github username to initiate contribution.
=> chore: add initial contribution 🚀 

package.json
Fixes an issue with running the `dev:apps` command on Windows.
=> fix: update `dev:apps` command to work on windows 🪟

apps/admin-dashboard/app/routes/_dashboard.applications.tsx
Updates the ordering/formatting of the applications table.
=> feat: switch ordering of columns in applications table ↪️

apps/admin-dashboard/app/routes/_dashboard.applications.tsx
Fixes a minor issue with the spacing of the "Reviewed By" column.
=> fix: update width of cramped columns in applications 📏

apps/member-profile/.env.example, apps/member-profile/app/routes/_profile.resume-books.$id.tsx, apps/member-profile/app/shared/constants.server.ts, apps/member-profile/app/shared/constants.ts, packages/core/package.json, packages/core/src/modules/airtable/use-cases/create-airtable-record.ts, packages/core/src/modules/resume-book/index.server.ts, packages/core/src/modules/resume-book/index.ts, packages/core/src/modules/resume-book/resume-book.types.ts, packages/core/src/modules/resume-book/use-cases/submit-resume.ts, packages/db/src/migrations/20240712030529_resume_book_submissions.ts
=> feat: submit resume to resume book (1/x) 📚

packages/core/src/modules/application/queries/list-applications.ts
This PR fixes an issue with an ambiguous column name in the application query.
=> fix: ambiguous column name in applications query ❗️

packages/core/src/modules/application/use-cases/accept-application.ts
Closes [#94](https://github.com/colorstackorg/oyster/issues/94)
- Removes applications with the same email of accepted application
_Note:_ Delete applications w/ same email BEFORE student is created, b/c Foreign Key error when deleting app after student is created
**3 pending applications w/ same email**
**0 pending applications**
**+1 accepted application**
**+1 students**
=> fix: remove duplicates of accepted application ❌

apps/member-profile/app/routes/_profile.resume-books.$id.tsx, apps/member-profile/app/shared/components/profile.personal.tsx, packages/core/src/modules/resume-book/index.server.ts, packages/core/src/modules/resume-book/queries/get-resume-book.ts, packages/core/src/modules/resume-book/resume-book.types.ts, packages/core/src/modules/resume-book/use-cases/submit-resume.ts, packages/db/src/migrations/20240715221033_resume_book_member_1.ts, packages/types/src/domain/student.ts, packages/types/src/index.ts
This PR implements the personal information based fields for the resume book.
=> feat: personal information for resume book 📚

apps/member-profile/app/routes/_profile.resume-books.$id.tsx, packages/core/src/modules/resume-book/resume-book.types.ts, packages/core/src/modules/resume-book/use-cases/submit-resume.ts, packages/db/src/migrations/20240716041601_resume_book_education.ts
=> feat: use education experience in resume book 📚

apps/member-profile/app/routes/_profile.resume-books.$id.tsx, packages/core/src/modules/resume-book/resume-book.types.ts, packages/core/src/modules/resume-book/use-cases/submit-resume.ts, packages/db/src/migrations/20240716051316_resume_book_specific.ts
=> feat: add job search specific fields to resume book 📚

apps/member-profile/app/routes/_profile.resume-books.$id.tsx, packages/core/src/modules/resume-book/index.server.ts, packages/core/src/modules/resume-book/queries/get-resume-book-submission.ts, packages/core/src/modules/resume-book/queries/get-resume-book.ts, packages/core/src/modules/resume-book/use-cases/submit-resume.ts
=> feat: support for editing a resume book submission 📚

packages/db/src/migrations/20240717040814_fix_casing_issue.ts, packages/db/src/use-cases/create-database-connection.ts
This PR reverts the `underscoreBeforeDigits` option.
=> fix: casing issue with the `underscoreBeforeDigits` option ❗️

apps/member-profile/app/routes/_profile.resume-books.$id.tsx, packages/core/src/modules/notification/use-cases/send-email.ts, packages/core/src/modules/resume-book/use-cases/submit-resume.ts, packages/email-templates/emails/resume-submitted.tsx, packages/email-templates/src/index.ts, packages/email-templates/src/types.ts
=> feat: email template for resume submitted/resubmitted 📫

apps/member-profile/app/routes/_profile.points.tsx, packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/gamification/use-cases/grant-gamification-points.ts, packages/core/src/modules/resume-book/use-cases/submit-resume.ts, packages/db/src/migrations/20240717054613_resume_book_gamification.ts, packages/types/src/domain/gamification.ts
=> feat: add gamification for submitting resume 📚

apps/member-profile/app/routes/_profile.resume-books.$id.tsx, packages/core/src/modules/resume-book/resume-book.types.ts, packages/core/src/modules/resume-book/use-cases/submit-resume.ts, packages/ui/src/components/form.tsx
This PR makes submitting another resume optional when resubmitting the entire resume book form.
=> feat: make resume file optional when resubmitting 📚

apps/member-profile/app/routes/_profile.resume-books.$id.tsx, packages/core/src/modules/resume-book/queries/get-resume-book.ts
=> feat: respect the start/end date of a resume book 📚

apps/member-profile/app/routes/_profile.resume-books.$id.tsx
=> fix: confirmation state after submitting resume book 📚

apps/member-profile/app/routes/_profile.resume-books.$id.tsx
=> feat: update ux details for resume book submission 📚

packages/core/src/modules/resume-book/resume-book.types.ts
=> fix: issue with timezone for resume book creation 📚

packages/core/src/modules/resume-book/resume-book.types.ts
=> fix: issue with timezone for resume book creation pt. 2 📚

apps/admin-dashboard/.env.example, apps/admin-dashboard/app/entry.server.tsx, apps/admin-dashboard/app/routes/_dashboard.resume-books.tsx, apps/admin-dashboard/app/routes/api.toast.ts, apps/admin-dashboard/app/shared/constants.server.ts, apps/admin-dashboard/app/shared/hooks.ts
This PR adds the ability to copy a link to the resume book from the Admin Dashboard.
=> feat: add "copy resume book link" 🔗

packages/ui/src/components/table.tsx
Follow up to #379, forgot to add accompanying data cell.
=> fix: add empty data cell in table 🍽️

apps/admin-dashboard/app/routes/_dashboard.resume-books.tsx, packages/core/src/modules/resume-book/resume-book.core.ts, packages/ui/src/components/dashboard.tsx
=> feat: add google drive link in resume books table 📚

apps/member-profile/app/routes/_profile.resume-books.$id.tsx, packages/ui/src/components/select.tsx
=> fix: prevent duplicate preferences in resume submission 📚

apps/member-profile/app/entry.server.tsx, apps/member-profile/app/root.tsx, apps/member-profile/app/routes/_profile.resume-books.$id.tsx, packages/ui/src/components/select.tsx
- Adds a required checkbox to the resume book ensuring that the member has updated their education history and primary email.
- Moves the dayjs initialization code to the server.
- Adds the "closing" date/time of the resume book to the top of the page.
- Reverts logic around the `Select` component default value.
=> feat: add education history checkbox and end date to resume book 📚

apps/member-profile/app/routes/_profile.resume-books.$id.tsx
This PR implements a very clear warning message when the education history isn't updated.
=> feat: add clear message when education history isn't updated ❗️

apps/admin-dashboard/app/routes/_dashboard.resume-books.$id.edit.tsx, apps/admin-dashboard/app/routes/_dashboard.resume-books.create.tsx, apps/admin-dashboard/app/routes/_dashboard.resume-books.tsx, apps/admin-dashboard/app/shared/constants.ts, packages/core/package.json, packages/core/src/modules/resume-book/resume-book.core.ts, packages/core/src/modules/resume-book/resume-book.types.ts, packages/core/src/modules/resume-book/resume-book.ui.tsx
=> feat: edit resume book details 📚

apps/admin-dashboard/app/routes/_dashboard.events.tsx
This PR adds the `# of Registrations` to the `Events` table in the Admin Dashboard.
=> feat: add "# of registrations" to events table #️⃣

apps/admin-dashboard/app/routes/_dashboard.resume-books.$id.edit.tsx, apps/admin-dashboard/app/routes/_dashboard.resume-books.create.tsx, apps/admin-dashboard/app/routes/_dashboard.resume-books.tsx, apps/member-profile/app/routes/_index.tsx, apps/member-profile/app/routes/_profile.tsx, packages/core/src/modules/feature-flag/feature-flag.types.ts, packages/core/src/modules/resume-book/resume-book.core.ts, packages/core/src/modules/resume-book/resume-book.types.ts, packages/core/src/modules/resume-book/resume-book.ui.tsx, packages/db/src/migrations/20240722215430_resume_book_tab.ts, packages/ui/src/components/dashboard.tsx, packages/ui/src/components/table.tsx
Related to #385.
- Adds a `hidden` field to the resume book.
- Adds a tab for the Resume Book in the Member Profile if there is an active/visible one.
- Updates the hover state for the navigation items in the dashboard layout.
=> feat: add `hidden` capability for resume books 🙈

CONTRIBUTORS.yml
Add name to `CONTRIBUTORS.yml` file.
=> chore: my first contribution 🤖

apps/admin-dashboard/app/routes/_dashboard.students.$id.remove.tsx, apps/admin-dashboard/app/routes/_dashboard.students.tsx, packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/member/events/member-removed.ts, packages/email-templates/emails/components/email.tsx, packages/email-templates/emails/student-removed.tsx, packages/email-templates/src/types.ts
This PR updates the Code of Conduct violation email.
=> feat: update code of conduct violation email 💬

apps/admin-dashboard/app/routes/_dashboard.events.$id.import.tsx, apps/admin-dashboard/app/routes/_dashboard.students.import.programs.tsx, apps/admin-dashboard/app/routes/_dashboard.students.import.resources.tsx, apps/admin-dashboard/app/routes/_dashboard.students.import.scholarships.tsx, apps/admin-dashboard/app/routes/_dashboard.surveys.$id.import.tsx, apps/member-profile/app/routes/_profile.resources.$id_.edit.tsx, apps/member-profile/app/routes/_profile.resources.add.tsx, apps/member-profile/app/routes/_profile.resume-books.$id.tsx, apps/member-profile/app/shared/components/resource-form.tsx, packages/core/src/modules/resource/resource.types.ts, packages/core/src/modules/resume-book/resume-book.core.ts, packages/core/src/modules/resume-book/resume-book.types.ts, packages/core/src/shared/utils/zod.utils.ts, packages/ui/src/components/file-uploader.tsx, packages/ui/src/index.ts
This PR is a follow up to #337, and uses the `FileUploader` component where possible.
=> feat: replace all native file inputs w/ `FileUploader` 🗂️

apps/admin-dashboard/app/routes/_dashboard.oyster.contributors.tsx
This PR adds a loading state for the slow GitHub API call to fetch Oyster stats. Follow up to #390.
=> feat: add loading state for slow github api request ⏰

apps/admin-dashboard/app/routes/_dashboard.events.$id.delete.tsx, apps/admin-dashboard/app/routes/_dashboard.events.tsx, apps/admin-dashboard/app/shared/constants.ts, packages/core/src/modules/event/event.core.ts
This PR adds the ability to delete an event and its associated data (ie: registrations, attendees and more).
=> feat: delete event and associated data 🚮

apps/member-profile/app/routes/_profile.points.tsx, packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/application/application.core.ts, packages/core/src/modules/gamification/gamification.core.ts, packages/core/src/modules/gamification/gamification.types.ts, packages/core/src/modules/gamification/gamification.ui.tsx, packages/db/src/migrations/20240730223045_referral_gamification.ts
Related to #420. Adds the corresponding gamification for it.
=> feat: add gamification for referrals 💰

apps/admin-dashboard/app/routes/_dashboard.tsx, packages/ui/src/components/dashboard.tsx, packages/ui/src/components/table.tsx
This PR fixes a small change that was made in #426.
=> fix: table overflow styling 🏓

CONTRIBUTING.md, README.md
This PR addresses a lot of the issues that come up with new contributors getting set up by simplifying the steps to get started.
=> docs: simplify the `CONTRIBUTING.md` guide 🍃

apps/member-profile/app/routes/_profile.resume.review.tsx, packages/core/src/modules/ai/ai.core.ts, packages/core/src/modules/resume/resume.core.ts, packages/core/src/shared/utils/core.utils.ts, packages/core/src/shared/utils/rate-limiter.ts
Follow up to #439.
This PR adds rate limiting to the Anthropic call, as well as better error handling.
=> fix: add rate limiting + error handling to ai module 🛑

apps/member-profile/app/routes/_profile.resume-books.$id.tsx, apps/member-profile/app/routes/_profile.resume.review.tsx, packages/core/src/member-profile.server.ts, packages/core/src/modules/resume/resume.core.ts
This PR:
- Adds the logos/names of the companies who are sponsoring a resume book.
- Refactors the caching logic of the resume feedback to live in `core`.
=> feat: add company sponsor logos to resume book 🏙️

packages/core/src/modules/airtable/airtable.core.ts, packages/core/src/modules/member/member.worker.ts
This PR fixes a lazy mistake -- follow up to #451.
=> fix: use airtable id when bulk updating ❗️

CONTRIBUTING.md, apps/member-profile/app/routes/_profile.points.tsx
This PR:
- Updates the contribution documentation to start Docker Desktop after installation.
- Fixes a small issue with showing emojis in the activity history.
=> docs: update docker desktop instructions 🎬

packages/core/src/modules/feed/feed.core.ts
Follow up to #265 -- adds a link to the resource in the Member Profile and updates bold/italics.
=> feat: update formatting of daily feed notification 🔗

packages/core/src/modules/resume/resume.core.ts
This PR fixes an issue that was reported where an error occurs parsing the JSON data from the AI completion.
=> fix: prompt for resume review to return json ❗️

apps/member-profile/app/routes/_profile.home.activation.tsx
=> feat: add status pill for activation modal 💊

packages/core/src/modules/feed/feed.ts, packages/core/src/modules/member/member.ts
This PR builds a reusable helper called `buildFullName` which incorporates a member's preferred name.
=> feat: include preferred name in reusable helper 👋

apps/member-profile/app/routes/_profile.directory.tsx, packages/core/src/modules/feed/feed.ts
This PR supports a search param called `joinedDirectoryDate` in the Member Directory and updates the feed notification accordingly.
=> feat: support querying by join date in member directory 📆

apps/member-profile/app/entry.server.tsx, apps/member-profile/app/routes/_profile.profile.integrations.tsx, apps/member-profile/app/routes/_profile.recap.$date.tsx, apps/member-profile/app/routes/_profile.resume-books.$id.tsx, packages/core/src/infrastructure/bull/bull.ts, packages/core/src/modules/application/application.core.ts, packages/core/src/modules/application/application.ui.tsx, packages/db/src/scripts/create-migration.ts, packages/ui/src/components/file-uploader.tsx, packages/ui/src/components/pagination.tsx, packages/utils/src/index.test.ts, packages/utils/src/index.ts
This PR removes the `iife` function in favor of the `run` function.
=> refactor: deprecate `iife` in favor of `run` 🏃‍♀️

apps/admin-dashboard/app/routes/_dashboard.schools.$id.edit.tsx, apps/admin-dashboard/app/routes/_dashboard.schools.tsx, packages/core/src/modules/education/education.core.ts, packages/core/src/modules/education/education.types.ts, packages/core/src/modules/education/education.ui.tsx, packages/db/src/migrations/20240827233709_school_tags.ts
This PR adds the `tags` field to the `schools` table, which will allow us to see which schools are HBCU or HSI.
=> feat: add tags to schools (ie: hbcu, hsi) 🎓

CONTRIBUTORS.yml
Added name to CONTRIBUTORS.yml!
=> chore: my first contribution 💯

packages/core/src/modules/feed/feed.ts
This PR builds upon #467 and #470, adding a case to the feed message when there is only 1 member who joined, 1 resource added, and/or 1 review added.
=> fix: add singular case to feed message 🔠

packages/core/src/modules/ai/ai.ts, packages/core/src/modules/pinecone.ts, packages/core/src/modules/slack/slack.ts
This PR updates the way we retrieve messages that Pinecone returns, given that Pinecone stores top-level threads and not individual messages.
=> feat: group threads together for pinecone embeddings 🌲

packages/core/src/modules/feed/feed.ts
This PR fixes a bug in #484 where the incorrect variables were being checked. Now, the correct case (singular or plural) should be added for all things in the feed message (resources, company reviews, and members added).
=> fix: add singular case to feed message pt 2 🔠

.github/scripts/manage-issues.js, .github/workflows/issue-management.yml
This PR fixes a silly mistake I made on the last PR!
=> fix: pipeline readability + bug w/ arguments 🐞

packages/types/src/domain/student.ts, packages/types/src/shared/zod.ts
=> fix: optional phone number has required behavior ❗️

apps/member-profile/app/routes/_profile.home.claim-swag-pack.tsx
This PR adds a dummy route to reduce swag pack migration confusion.
=> feat: add 404 route + text to reduce swag confusion 🧠

packages/core/src/modules/member/member.worker.ts
=> feat: add relative points to airtable 🏆

packages/core/src/modules/member/member.worker.ts
=> fix: coalesce point totals for airtable updates ❗️

packages/db/src/migrations/20241007155803_hello world.ts, packages/db/src/scripts/create-migration.ts
Closes #551 
Updates the import state in the Create Migration script.
=> refactor: update import in migration creation script 📝

packages/db/src/migrations/20241008025612_remove_member_cascade.ts
This PR fixes an issue w/ removing a member caused by not cascading deletes.
=> fix: on delete cascade for member references 🗑️

packages/db/src/migrations/20241008213548_opportunities.ts
This PR adds the following tables, as well as adds indices for them:
- `opportunities`
- `opportunity_bookmarks`
- `opportunity_tags`
- `opportunity_tag_associations`
It also alters the `completed_activities` to support gamification.
=> feat: migration for opportunities 🚀

apps/admin-dashboard/app/shared/components/card.tsx, apps/member-profile/app/routes/_profile.companies.tsx, apps/member-profile/app/routes/_profile.events.past.tsx, apps/member-profile/app/routes/_profile.events.upcoming.tsx, apps/member-profile/app/routes/_profile.profile.integrations.tsx, apps/member-profile/app/shared/components/card.tsx, apps/member-profile/app/shared/components/resource.tsx, packages/ui/src/components/file-uploader.tsx
This PR shrinks all rounded corners that were previously `rounded-3xl` to `rounded-2xl`.
=> feat: reduce rounding of corners on `card` ♠️

apps/member-profile/app/routes/_profile.opportunities.$id_.delete.tsx, apps/member-profile/app/shared/constants.ts, packages/core/src/modules/opportunity/opportunity.ts
This PR implements the ability to delete an opportunity as well as a check to see if a member has write permission for an opportunity!
=> feat: delete opportunity + write permission check 🚮

apps/member-profile/app/routes/_profile.companies.tsx, apps/member-profile/app/routes/_profile.companies_.$id.tsx, packages/core/src/modules/employment/queries/get-company.ts, packages/core/src/modules/employment/queries/list-companies.ts
This PR supports open opportunities found for a company in both the list view of companies as well as the individual view.
=> feat: support opportunities in company pages 💼

apps/member-profile/app/routes/_profile.opportunities.$id_.bookmark.tsx, apps/member-profile/app/routes/_profile.points.tsx, packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/gamification/gamification.core.ts, packages/core/src/modules/gamification/gamification.types.ts, packages/core/src/modules/opportunity/opportunity.ts
This PR ships the ability to bookmark an opportunity, including the UI button to do so. This also supports gamification...whenever someone bookmarks an opportunity, the original poster will get 10 points!
=> feat: ability to bookmark opportunities 🔖

apps/member-profile/app/routes/_profile.opportunities.$id_.edit.tsx, apps/member-profile/app/routes/_profile.opportunities.tags.tsx, packages/core/src/member-profile.ui.ts, packages/core/src/modules/opportunity/opportunity.ts, packages/core/src/shared/utils/color.utils.ts, packages/ui/src/components/multi-combobox.tsx
This PR implements the ability to edit opportunities and more.
=> feat: ability to edit opportunities ✏️

apps/member-profile/app/routes/_profile.opportunities.$id.tsx, apps/member-profile/app/routes/_profile.opportunities.tsx, apps/member-profile/app/shared/components/slack-message.tsx, packages/ui/package.json, packages/ui/src/components/button.tsx, packages/ui/src/components/filter.tsx, packages/ui/src/index.ts
Implements the opportunities table w/ the ability to filter by:
- Tags
- Company
- Date Posted
- Status
- Your Bookmarks
Also introduces some new `Filter` based components to `ui`.
=> feat: opportunities table w/ filtering 🚀

apps/member-profile/app/routes/_profile.opportunities.$id.tsx, apps/member-profile/app/routes/_profile.opportunities.tsx, packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/mixpanel.ts, packages/core/src/modules/opportunity/opportunity.ts
This PR tracks 3 events:
- `Page Viewed` (Opportunities)
- `Opportunity Bookmarked`
- `Opportunity Viewed`
This also adds a `sendNotification` boolean value upon opportunity creation.
=> feat: track opportunity events w/ mixpanel 🟣

packages/core/src/modules/opportunity/opportunity.ts
This fixes a bug that doesn't grant write permission to admin.
=> fix: bug w/ opportunity write permission 🐞

apps/member-profile/app/routes/_profile.opportunities.tsx, packages/core/src/modules/opportunity/opportunity.ts
This PR:
- Fixes a bug that would crash if a company wasn't populated.
- Fixes a visual bug where the company name was not being truncated within the cell.
- Fixes a bug where the Crunchbase search is way off from the name we get back from AI...so we now do a naive "similarity" check.
- Limits the # of tags to 5 when generating w/ AI.
=> fix: usability issues w/ opportunities 🐞

apps/member-profile/app/routes/_profile.opportunities.tsx, packages/core/src/modules/opportunity/opportunity.ts
This PR fixes a crash that happened if an opportunity wasn't associated w/ a member. It also prevents a second notification being sent to the opportunity thread if it was already refined before.
=> fix: better handling of opportunity edge cases ❗️

apps/member-profile/app/routes/_profile.opportunities.$id_.bookmark.tsx, packages/core/src/modules/opportunity/opportunity.ts
This PR implements optimistic UI for bookmarking an opportunity, and it also fixes a bug where the AI was setting the date to the past since it doesn't know the date.
=> fix: optimistic bookmarking + ai expiration date ❗️

CONTRIBUTORS.yml
Added name to `CONTRIBUTORS.yml`
=> chore: my first contribution ✨

packages/core/src/modules/member/events/member-activated.ts
This PR updates activation gift cards to expire after 2 weeks instead of 1.
=> feat: set gift card expiration to 2 weeks 📆

packages/core/src/modules/opportunity/opportunity.ts
Fixes an issue that attempts to the update the opportunity before it is created.
=> fix: create opportunity before refining it ❗️

packages/core/src/modules/slack/slack.ts
Fixes a small issue with references in the AI Chatbot feature.
=> fix: parsing issue w/ chatbot references ❗️

apps/admin-dashboard/railway.json, packages/db/src/use-cases/create-database-connection.ts
This reverts the changes since the private networking attempt wasn't successful.
=> fix: revert attempt to use private networking in pipeline ↩️

packages/db/src/migrations/20241112075600_drop_mailchimp_tables.ts
Follow up to #621, drops the email marketing related tables. Note that we already exported all of this data in case we need it in the future for whatever reason (though unlikely).
=> chore: drop email marketing tables 🚮

CONTRIBUTORS.yml
Adding my username to CONTRIBUTORS.yml in Oyster
=> chore: first contribution 🚀

apps/admin-dashboard/railway.json
Update the database connection string to use the `DATABASE_PUBLIC_URL` during the Railway build phase, since we updated the environment variable to use the private network URL at runtime.
=> chore: try private networking for database in admin dashboard 🔒 

apps/api/railway.json, apps/member-profile/railway.json
Follow up to #626, enabling the private database URL in both the `api` and `member-profile`.
=> chore: use private database url in all apps 🔒

apps/member-profile/app/routes/_profile.offers._index.tsx, apps/member-profile/app/routes/_profile.offers.full-time.$id.tsx, apps/member-profile/app/routes/_profile.offers.full-time.tsx, apps/member-profile/app/routes/_profile.offers.internships.$id.tsx, apps/member-profile/app/routes/_profile.offers.internships.tsx, apps/member-profile/app/routes/_profile.offers.tsx, apps/member-profile/app/routes/_profile.opportunities.$id.tsx, apps/member-profile/app/routes/_profile.opportunities.tsx, apps/member-profile/app/routes/_profile.tsx, apps/member-profile/app/shared/components/index.tsx, apps/member-profile/app/shared/components/offer.tsx, packages/core/src/modules/compensation/job-offers.ts, packages/ui/src/components/filter.tsx
This PR is a follow up that cleans up the code for the offers UI.
=> feat: clean up ui for internship/full-time offers 🧹

packages/core/src/modules/compensation/job-offers.ts
This PR fixes an issue with the query for Slack messages which are linked to offers.
=> fix: query for backfilling offers ❗️

packages/core/src/modules/compensation/job-offers.ts
This PR updates the keyword search to support the different ways that a user may format their job offer message.
=> fix: share opportunity doesn't work w/ special formatting ❗️

apps/member-profile/app/routes/_profile.offers.full-time.$id_.delete.tsx, apps/member-profile/app/routes/_profile.offers.full-time.tsx, apps/member-profile/app/routes/_profile.offers.internships.$id_.delete.tsx, apps/member-profile/app/routes/_profile.offers.internships.tsx, packages/core/src/modules/compensation/job-offers.ts
This PR support salary ranges when filtering internship and full-time offers. This also supports deleting an offer via the UI.
=> feat: support salary ranges for filters + deleting offers 🚮

apps/member-profile/app/routes/_profile.offers.full-time.$id.tsx, apps/member-profile/app/routes/_profile.offers.full-time.$id_.edit.tsx, apps/member-profile/app/routes/_profile.offers.internships.$id.tsx, apps/member-profile/app/routes/_profile.offers.internships.$id_.edit.tsx, apps/member-profile/app/shared/components/offer.tsx, packages/core/src/modules/compensation/job-offers.ts
This PR supports editing both internship and full-time offers.
=> feat: support editing offers ✍️

apps/member-profile/app/routes/_profile.offers.full-time.tsx, apps/member-profile/app/routes/_profile.offers.internships.tsx, apps/member-profile/app/shared/components/offer.tsx, packages/core/src/modules/compensation/job-offers.ts
This PR implements aggregated offer data for both internships and full-time. Also fixes a location issue that doesn't use the abbreviated state.
=> feat: show aggregated offer information 🚀

apps/member-profile/app/routes/_profile.offers.full-time.$id_.edit.tsx, apps/member-profile/app/routes/_profile.offers.internships.$id_.edit.tsx, packages/core/src/modules/compensation/job-offers.ts, packages/ui/src/components/input.tsx, packages/ui/src/index.ts
This PR implements a `DollarInput` which makes it easier to handle USD input.
=> fix: implement dollar input for editing offer info 💰

apps/member-profile/app/routes/_profile.offers.full-time.$id_.edit.tsx, apps/member-profile/app/routes/_profile.offers.full-time.add.tsx, apps/member-profile/app/routes/_profile.offers.internships.$id_.edit.tsx, apps/member-profile/app/routes/_profile.offers.internships.add.tsx, packages/core/src/modules/compensation/job-offers.ts
This PR implements the ability to create an internship/FT offer from the Member Profile, and also
=> feat: ability to create internship/full-time offer from profile 🚀

apps/member-profile/app/routes/_profile.offers.internships.$id.tsx, apps/member-profile/app/routes/_profile.offers.internships.$id_.edit.tsx, apps/member-profile/app/routes/_profile.offers.internships.add.tsx, packages/core/src/modules/compensation/job-offers.ts, packages/db/src/migrations/20241121004747_internship_offer_bonus.ts
This PR removes the `sign_on_bonus` for internships, given that it's not common.
=> chore: scrap sign-on bonus for internships 🗑️

apps/member-profile/app/routes/_profile.offers.full-time.$id.tsx, apps/member-profile/app/routes/_profile.offers.full-time.tsx, apps/member-profile/app/routes/_profile.offers.internships.$id.tsx, apps/member-profile/app/routes/_profile.offers.internships.tsx, packages/core/src/modules/mixpanel.ts
This PR shows the relative posted time in the offer tables and also adds the `Offer Viewed` event.
=> feat: show offer posted time and add mixpanel event 🚀

packages/core/src/modules/compensation/offers.ui.tsx
This PR adds placeholder text to help members understand how to format their location.
=> fix: add placeholder text for location to help formatting ❗️

apps/member-profile/app/routes/_profile.offers.tsx
This PR better supports mobile for the offers layout.
=> fix: support mobile layout for offers ❗️

apps/member-profile/app/routes/_profile.offers.full-time.$id_.edit.tsx, apps/member-profile/app/routes/_profile.offers.internships.$id_.edit.tsx
More intuitive naming for the button to save an edit on an offer.
=> fix: change offer button naming from edit to save ❗️

apps/member-profile/app/routes/_profile.offers.full-time.tsx, apps/member-profile/app/routes/_profile.offers.internships.tsx, packages/core/src/modules/compensation/offers.ts, packages/ui/src/components/filter.tsx
This PR removes the notification that gets sent to the `#community-compensation` channel and also updates the filter popover to take max height for the hourly rate / TC.
=> fix: scrap offer notification + update filter popover to max height ❗️

packages/core/src/modules/slack/use-cases/add-slack-message.ts
Revert to checking the database for 100 replies because Slack is seemingly not following their documentation in sending the `message.reply_count` property on the `message_replied` subevent.
=> fix: slack api not returning `reply_count` in `message_replied` event ❗️

packages/db/src/migrations/20241207173128_drop_migrations.ts
Drops the old `migrations` table before we were using kysely.
=> chore: drop old migrations table 🚮

packages/ui/package.json, packages/ui/src/components/select.tsx, packages/ui/src/components/select.v2.tsx, yarn.lock
This PR implements a new `Select` component using the Radix [primitive](https://www.radix-ui.com/primitives/docs/components/select). This has better accessibility than our manual implementations and better design than the native implementation.
=> feat: implement select component (v2) using radix 🚀

apps/member-profile/app/entry.client.tsx, apps/member-profile/app/routes/_profile.tsx, packages/core/src/modules/feature-flags/queries/is-feature-flag-enabled.ts, packages/core/src/modules/slack/slack.ts, packages/core/src/modules/slack/use-cases/add-slack-message.ts, packages/db/src/migrations/20241212172613_perf_fixes.ts
This PR fixes various performance issues, most notably the query to get the "active" status on the home page.
=> fix: various performance improvements ⚡️

packages/db/src/migrations/20241213175343_event_perf_fixes.ts
Slight increase in performance which changing the order.
=> fix: update the order of the unique constraint in `event_attendees` ❗️

apps/member-profile/app/routes/_profile.events.past.tsx
This PR redirects from `/events/past` to `/events`.
=> fix: redirect from `/events/past` ❗️

apps/member-profile/app/entry.server.tsx, packages/core/src/infrastructure/pinecone.ts
Specifies the `fetchApi` option when initializing the Pinecone SDK to get rid of this log:
```
Failed to find any user-provided fetch implementation. Using global fetch implementation.
```
=> chore: get rid of noisy pinecone fetch log 🪵

CONTRIBUTORS.yml, apps/member-profile/app/routes/_profile.companies.tsx, apps/member-profile/app/routes/_profile.companies_.$id.tsx, apps/member-profile/app/shared/components/index.tsx
Closes #696 
- Fixed stretched company logos in opportunities, offers, and companies pages.
=> fix: stretched company logos 🏢

apps/api/src/routers/oauth.router.ts
This PR fixes an issue that causes an API crash having to do with OAuth parsing logic.
=> fix: move oauth parsing inside try/catch ❗️

CONTRIBUTORS.yml
Added name to `CONTRIBUTORS.yml`.
=> chore: my first contribution

apps/member-profile/app/routes/_profile.opportunities.$id.tsx, packages/core/src/modules/opportunities.ts
This PR fixes an issue that prevents checking for expiration for all opportunities. Also fixes a grammatical issue on the opportunity details modal it's already expired.
=> fix: issue with opportunity expiration job + label ❗️

packages/core/src/modules/opportunities.ts
This PR handles errors with browsing a web page in the opportunity expiration check.
=> fix: resilience when opportunity expiration check takes too long ❗️

apps/member-profile/app/routes/_profile.opportunities.tsx
This PR adds the relative timestamp when an opportunity was posted in the opportunities table.
=> feat: add time that opportunity was shared ⏰

packages/core/src/modules/opportunities.ts, packages/db/src/migrations/20250226235150_opportunity_link.ts
Instead of having to pull the link out of an opportunity at runtime whenever we want to show it, instead we should just store it on the opportunity itself.
=> feat: store the first link on an opportunity 🔗

apps/member-profile/app/routes/_profile.opportunities.$id.tsx, apps/member-profile/app/routes/_profile.opportunities.$id_.refine.tsx, packages/core/src/infrastructure/bull.types.ts, packages/core/src/modules/opportunities.ts
This PR automatically checks if an individual opportunity has expired after a member has opened an individual opportunity.
=> feat: check expiration of individual opportunity after opening modal ❎

packages/core/src/modules/opportunities.ts
This PR is a follow up to the removal of nearly 350 tags in the opportunities table. We update the prompt which chooses tags to be more selective instead of exhaustive.
=> fix: update opportunities prompt to return less tags 🏷️

apps/admin-dashboard/app/routes/_dashboard.applications.$id._index.tsx, apps/admin-dashboard/app/routes/_dashboard.applications.tsx, apps/admin-dashboard/app/routes/_dashboard.bull.$queue.tsx, apps/admin-dashboard/app/routes/_dashboard.events.tsx, apps/admin-dashboard/app/routes/_dashboard.feature-flags.tsx, apps/admin-dashboard/app/routes/_dashboard.gamification.activities.tsx, apps/admin-dashboard/app/routes/_dashboard.onboarding-sessions.tsx, apps/admin-dashboard/app/routes/_dashboard.resume-books.tsx, apps/admin-dashboard/app/routes/_dashboard.schools.tsx, apps/admin-dashboard/app/routes/_dashboard.students.tsx, apps/member-profile/app/routes/_profile.directory.tsx, packages/core/src/modules/admins/admins.ui.tsx, packages/core/src/modules/employment/ui/work-experience.tsx, packages/ui/src/components/dropdown.tsx, packages/ui/src/components/table.tsx, packages/ui/src/index.ts
Closes #616. This PR also does a really big refactor of the `Dropdown` component.
- The biggest change is that we move the `open` state inside of the dropdown context instead of having it passed in.
- To support this, we added a `Dropdown.Trigger` component which wraps around whatever button/element was previously responsible for opening the dropdown.
- Renamed the `Dropdown.Container` to `Dropdown.Root` to follow the Radix UI naming convention.
=> fix: close dropdown when clicking on item ❗️

apps/member-profile/app/routes/_profile.opportunities.$id.tsx, packages/core/src/modules/opportunities.ts, packages/db/src/migrations/20250304183129_opportunity_reports.ts, packages/db/src/scripts/seed.ts, packages/ui/src/components/dropdown.tsx, packages/ui/src/components/icon-button.tsx
This PR supports the ability to report an opportunity as closed/duplicated/broken link.
- Adds the `opportunity_reports` table including a `reason` for reporting.
- Adds a "Report Opportunity" button in the individual opportunity modal, which allows you to select a reason.
- If an opportunity is reported by 2 people OR an admin, the opportunity will be marked as expired and thus taken off the board.
- Also removes the not null constraint from the `slack_channel_id` and `slack_message_id` on the `opportunities` table.
- Updates the seed script to include companies and opportunities (and their related data).
=> feat: reporting when opportunity is broken/closed/duplicated ❗️

packages/core/src/infrastructure/puppeteer.ts, packages/core/src/modules/opportunities.ts
This PR sends a notification to the poster of an opportunity if the automated refinement process fails.
=> feat: send notification when automated refinement fails ❗️

packages/core/src/infrastructure/puppeteer.ts
Logs the Puppeteer status code after requesting a web page.
=> chore: log puppeteer status code 🪵

packages/core/src/modules/opportunities.ts
This PR stops the ability to create new tags that are generated using AI in the `refineOpportunity` function.
=> fix: stop creating new opportunity tags 🏷️

packages/core/src/modules/notifications/use-cases/send-slack-notification.ts
This PR disables unfurling of links that we send in our Slack notifications.
=> feat: disable unfurling of slack links 🔗

packages/db/src/migrations/20250307224500_graduation_date.ts, packages/db/src/scripts/seed.ts
This PR:
- Adds the `graduation_date` field to the `applications` and `students` tables.
- Updates the `seed` script to include more data to start off with.
=> chore: add `graduation_date` and update seed data 🌱

packages/core/src/modules/compensation/offers.ts, packages/core/src/modules/compensation/offers.ui.tsx
This PR:
- Implements the `extractLocation` function which is used when adding/editing both internship/full-time offers through the Member Profile. Example: `SF` -> `San Francisco, CA`.
=> feat: use ai to clean up offer locations 🪄

apps/member-profile/app/routes/_profile.directory.tsx, apps/member-profile/app/routes/_profile.recap.$date.members.tsx, apps/member-profile/app/routes/_profile.recap.$date.tsx, packages/core/src/modules/members/members.types.ts, packages/core/src/modules/members/queries/list-members-in-directory.ts
This PR fixes a couple bugs with the filtering in the member directory, including the filter for school and company.
=> fix: company/school filter in directory ❗️

apps/member-profile/app/routes/_profile.directory.tsx, packages/ui/src/components/filter.tsx
This PR updates the location and hometown filter to search for values in the database instead of the Google Maps API. This ensures that whatever location is selected is guaranteed to have a member in the result.
=> fix: constrain location/hometown filter to database 🔎

apps/member-profile/app/routes/_profile.directory.tsx, apps/member-profile/app/routes/_profile.offers.full-time.tsx, apps/member-profile/app/routes/_profile.offers.internships.tsx, apps/member-profile/app/routes/_profile.opportunities.tsx, apps/member-profile/app/shared/components/index.tsx
This PR fixes an issue with some hometowns/locations having different names but the same coordinates. Since the coordinates are the value we care about, we need to make sure that they are unique.
=> fix: duplicate locations/hometowns with same coordinates ❗️

apps/member-profile/app/routes/_profile.directory.tsx
This PR adds a member count to each filter option and sort the options in descending order based on those counts.
=> feat: add filter counts to directory filters 🔢

apps/member-profile/app/routes/_profile.directory.tsx
This PR fixes an issue which previously included members in filter counts despite them not being in the member directory. This also fixes an issue which showed a null value for companies.
=> fix: exclude members from count if not in directory ❗️

apps/member-profile/app/routes/_profile.directory.tsx, packages/db/src/migrations/20250312072423_directory_performance.ts
This PR speeds up various queries for directory filtering. The biggest improvement is adding an index on the `educations.student_id` field.
=> refactor: speed up queries for directory filtering ⚡️

apps/member-profile/app/routes/_profile.directory.tsx, packages/db/src/scripts/seed.ts, packages/ui/src/components/dashboard.tsx, packages/ui/src/components/filter.tsx
This PR:
- Adds a disclaimer to the location/hometown filter popover letting the user know about the distance filter.
- Fixes a bug with the `Dashboard.SearchForm` which didn't retain the search params on the page.
=> fix: add location disclaimer in filter + fix search form ❗️

apps/member-profile/app/routes/_profile.directory.tsx, apps/member-profile/app/routes/_profile.offers.full-time.tsx, apps/member-profile/app/routes/_profile.offers.internships.tsx, apps/member-profile/app/routes/_profile.opportunities.tsx, packages/ui/src/components/filter.tsx
This PR updates the member directory filters to all show by default. This also refactors the `ClearFiltersButton`.
=> feat: show all filters by default + update reset filter ui 🔎

apps/member-profile/app/routes/_profile.directory.tsx, apps/member-profile/app/routes/_profile.offers.full-time.tsx, apps/member-profile/app/routes/_profile.offers.internships.tsx, apps/member-profile/app/routes/_profile.opportunities.tsx, apps/member-profile/app/shared/components/index.tsx, packages/ui/src/components/filter.tsx
This PR:
- Updates the layout of filters in the directory page.
- Moved the `name` and `selectedValues` state into to the `FilterRoot` so that they can be used in different internal components.
- Removed the `checked` and `name` props from a `FilterItem`, since now we can use these from the filter's context.
- Created the `FilterList` component which is what has the max height baked into it, instead of the `FilterPopover`.
- Changes the `popover` prop on the `FilterButton` to default to `true`.
=> feat: support removing filters + refactor 🔄

apps/member-profile/app/routes/_profile.directory.tsx, apps/member-profile/app/routes/_profile.offers.full-time.tsx, apps/member-profile/app/routes/_profile.offers.internships.tsx, apps/member-profile/app/routes/_profile.opportunities.tsx, apps/member-profile/app/shared/components/index.tsx, packages/ui/src/components/filter.tsx
This PR updates the `Filter` component to support keyboard interactions (ie: `ArrowUp`, `ArrowDown`, `Enter`, `Escape`).
=> feat: support keyboard interactions on filters 🎹

packages/core/src/modules/education/education.ts, packages/ui/src/components/table.tsx
This PR fixes a bug which previously didn't propagate school name changes to Airtable member records.
=> fix: propagate school name changes to airtable ❗️

packages/core/src/modules/notifications/use-cases/send-email.ts, packages/email-templates/emails/application-accepted.tsx, packages/email-templates/emails/components/email.tsx
This PR:
- Uses a `noreply@colorstack.org` inbox for all transactional emails.
- Updates the welcome email content.
=> feat: use noreply email box + update welcome email 🚀

apps/admin-dashboard/app/routes/_dashboard.onboarding-sessions.tsx, apps/admin-dashboard/app/routes/_dashboard.tsx, apps/member-profile/app/routes/_profile.tsx, packages/ui/src/components/dashboard.tsx
This PR:
- Updates the `<Dashboard.NavigationLink>` component styling.
- Shrinks the dashboard sidebar by 30 pixels.
=> refactor: update dashboard navigation styling 🎨

apps/member-profile/app/routes/_profile.peer-help.tsx
This PR renames the Peer Help `Completed` section to `Closed`.
=> chore: rename the peer help completed section label to closed ❗️

apps/member-profile/app/routes/_profile.tsx, packages/core/src/modules/feature-flags/feature-flags.types.ts
This PR puts the `/points` page behind a feature flag.
=> chore: put points page behind feature flag ⛳️

packages/core/src/modules/applications/applications.ts
This PR supports filtering applications by a list of emails.
=> feat: support application email filter list 🚀

apps/member-profile/app/routes/_profile.home.tsx
This PR adds the [Chapters](https://colorstack.notion.site/colorstack-chapters-list) Notion to the home page of the Member Profile.
=> feat: add chapters list resource to home page 🚀

apps/admin-dashboard/app/routes/_dashboard.applications.$id._index.tsx, apps/member-profile/app/routes/_public.apply._index.tsx, packages/core/src/modules/applications/applications.ui.tsx
This PR updates the language copy on the family application.
=> chore: update application content + questions ✏️

apps/member-profile/app/routes/onboarding.community.tsx, apps/member-profile/app/routes/onboarding.slack.tsx
This PR fixes a small issue in the Slack invitation being sent only after the onboarding flow is completed.
=> fix: delay slack invitation till last step ❗️

packages/core/src/modules/applications/applications.ts
=> feat: update application auto rejection ❗️

apps/member-profile/app/routes/_profile.resources.tsx, packages/core/src/modules/resources/queries/list-resources.ts, packages/db/src/migrations/20250512230105_resource_upvotes_perf.ts
=> feat: support resource filters 🔎

packages/core/src/modules/peer-help.ts
=> fix: multiline quote for help request notification ❗️

apps/member-profile/app/routes/_profile.opportunities.tsx, apps/member-profile/app/shared/components/index.tsx
Updates the [listAllCompanies](https://github.com/colorstackorg/oyster/blob/eccbd74ac3f912e4a9be9f5e2848f293bc5a4d2e/apps/member-profile/app/routes/_profile.opportunities.tsx#L145-L160) function such that:
- it returns only companies that are linked with an active opportunity
- it shows the # of active opportunities for each company.
- it sorts the companies in descending order based on the # of active opportunities.
Updates the UI for the filter dropdown to show: 
- the # of active opportunities in parenthesis, example: Adobe (5)
Closes #735
=> feat: improve ux for filtering opportunities by company 🚀

apps/member-profile/app/routes/_profile.opportunities.tsx
=> feat: improve ux for filtering opportunities by tags 🚀

apps/member-profile/app/routes/_profile.profile.work.tsx, apps/member-profile/app/shared/queries/index.ts, packages/core/src/modules/linkedin.ts
This PR makes the following improvements to the LinkedIn sync:
- Sends a Slack notification when the sync happens, notifying the user of potential bad data.
- Adds a `isSchoolOnLinkedIn` and `isCompanyOnLinkedIn` which will help us with bad links.
- Separates the caching for the Apify integration
- Updates the toast message in the Member Profile to check Slack for a notification.
- Updates the rendering of the "other major" in a education experience.
=> fix: improve bad company/school links in linkedin sync 🔀

packages/core/src/modules/linkedin.ts
This PR ships a fix which ignores the `isSchoolOnLinkedIn` and `isCompanyOnLinkedIn` fields when generating changes, but keeps it for metadata purposes.
=> fix: ignore fields for generating linkedin differential ❗️

apps/member-profile/app/routes/schools.tsx, apps/member-profile/app/shared/components/education-experience.tsx, apps/member-profile/app/shared/queries/index.ts, packages/core/src/modules/education/education.ts, packages/core/src/modules/education/education.types.ts, packages/core/src/modules/education/education.ui.tsx, packages/db/src/migrations/20250614160954_school_linkedin.ts
This PR:
- Adds a `linkedin_id` and `logo_url` to the `schools` table.
- Updates the school searching functionality based on more relevant context.
- Updates the education experience UI for a member's profile to show the logo if present.
- Updates the `SchoolCombobox` to support rendering the logo.
=> feat: add linkedin id to schools and update search 🔍

apps/member-profile/app/routes/_profile.companies_.$id.tsx, apps/member-profile/app/shared/components/education-experience.tsx, packages/core/src/modules/education/use-cases/save-school-if-necessary.ts, packages/core/src/modules/employment/queries/list-work-experiences.ts, packages/core/src/modules/employment/ui/work-experience.tsx, packages/core/src/modules/linkedin.ts
This PR:
- Fixes a bug with fetching the location of a school using Apify.
- Fixes a bug with saving the location of a work experience.
- Implements a workaround for some bugs in the Apify scraper related to the `location` and `workplaceType`.
- Updates the work experience UI including showing description, duration, employment type, location type, and country (if not US). Also links to the company page.
- Displays the LinkedIn URL associated with each company on the individual company page.
- Updates the education experience UI by moving location to the bottom.
=> feat: update work experience/education ui 🎨

apps/member-profile/app/routes/_profile.companies_.$id.employees.tsx
This PR brings back the cards for current/past employees of a company.
=> refactor: reintroduce cards for current/past employees 🎨

CONTRIBUTING.md
This PR removes instructions on "first PR" given there's not many other issues to work on.
=> docs: wind down "first pr" instructions 🗒️

apps/admin-dashboard/app/entry.server.tsx, apps/admin-dashboard/app/root.tsx, apps/admin-dashboard/app/routes/_dashboard.admins.tsx, apps/admin-dashboard/app/routes/_dashboard.events.$id.delete.tsx, apps/member-profile/app/entry.server.tsx, apps/member-profile/app/root.tsx, apps/member-profile/app/routes/_profile.offers.internships.tsx, apps/member-profile/app/routes/_profile.peer-help.request.tsx, apps/member-profile/app/routes/_profile.peer-help.tsx, apps/member-profile/app/routes/onboarding.community.tsx, apps/member-profile/app/shared/components/index.tsx, apps/member-profile/app/shared/components/review-form.tsx, config/eslint/base.js, packages/core/src/modules/events/events.ts, packages/ui/src/components/address.tsx, packages/ui/src/components/dashboard.tsx, packages/ui/src/components/file-uploader.tsx, packages/ui/src/hooks/use-on-click-outside.ts
This PR:
- Adds the `'import/no-duplicates': ['error', { 'prefer-inline': true }]` to ESLint config.
- Runs `yarn lint:fix` to fix all violations of the rule.
=> chore: add `import/no-duplicates` rule to eslint config 🧹

.github/workflows/ci.yml, package.json
This PR specifies the `bun` version to use.
=> chore: specify bun version 1️⃣

packages/ui/src/components/profile-picture.tsx
=> fix: profile picture initials ❗️
