colorstackorg/oyster

CONTRIBUTING.md
Adds a guideline to contributing PR, which is to make the PR name all lowercase.
=> docs: add lowercase guideline for PR name ✏️

CONTRIBUTING.md, package.json, packages/core/src/infrastructure/database/scripts/seed.ts
**Note: This PR does not solve the root issue and we need to figure out a more sustainable way to support transpilation in our non-Vite parts of the codebase.**
- Removes references to `@colorstack/types` and `@colorstack/utils` in the `seed` script.
- Adds the top-level `db:seed` command, which references the `core` package command.
- Updates the documentation for seeding according to the above.
=> fix: remove need for transpilation in `db:seed` 🌱

package.json
It's a bit unintuitive, but after you install a new package, the auto-generated types that `kysely-codegen` generates are wiped out, and it will make the build fail if you try to build. If you recognize the issue, you'll simply run `yarn db:migrate` and everything will work again, but that is an extra step that is a bit cumbersome.
Instead, with this PR, after installation, we will automatically regenerate any types.
```json
"postinstall": "yarn workspace @oyster/core db:types"
```
Note that in the case of our CI workflow, the database will be empty at the time that the `postinstall` script runs, which causes no harm (nor does it add any benefit). This is mainly a development workflow optimization.
=> feat: add `postinstall` script to monorepo root 🌴

packages/types/src/index.ts, packages/ui/src/components/button.tsx, packages/ui/src/components/date-picker.tsx, packages/ui/src/hooks/use-on-click-outside.ts, packages/ui/src/index.ts, packages/utils/src/index.ts
This PR removes all instances of `export *` from all barrel files in our packages. That was a lazy way of exporting, not being mindful of everything we were exporting. With this change, we are intentional about everything that we're exporting.
=> refactor: remove `export *` from barrel files 🛢️

apps/admin-dashboard/app/routes/_dashboard.applications.tsx, apps/admin-dashboard/app/tailwind.css, apps/member-profile/app/routes/_profile.home.tsx, apps/member-profile/app/routes/_profile.profile.emails.tsx, apps/member-profile/app/tailwind.css, config/tailwind/tailwind.config.js, packages/ui/src/components/checkbox.tsx, packages/ui/src/components/pill.tsx, packages/ui/src/components/radio.tsx, packages/ui/src/components/spinner.tsx, packages/ui/src/components/toast.tsx, packages/ui/src/index.css, packages/ui/src/index.ts, packages/ui/src/utils/constants.ts
This PR does the folllowing:
- Removes all CSS color variables and uses Tailwind's functionality instead.
- Removes the `Color` type and replaces it with the `AccentColor`.
- Uses Tailwind's `theme()` function in CSS files to reference colors.
- Adds more colors to the base Tailwind config (ie: `error`, `success`, `gold`).
=> refactor: update colors in tailwind config 💨

CONTRIBUTING.md
This PR adds documentation that guides a newcomer to their first PR.
=> docs: "your first pull request" 💻

package.json
This PR:
- Removes the `postinstall` step as in retrospect, is a bit unintuitive and breaks the `CONTRIBUTING.md` onboarding flow.
- Adds the `db:types` command to the root.
=> feat: remove the `postinstall` step 🎆

CONTRIBUTING.md, packages/core/src/modules/notification/use-cases/send-email.ts
This PR:
- Removes the `shouldSendEmail` function, which previously didn't allow emails to be sent to non-`@colorstack.org` emails in development.
- Adds documentation on logging into applications, and setting up the relevant integrations.
We can still probably prevent accidental emails from being sent in the dev environment, but we'll need to think through that a little bit more.
=> fix: allow emails to be sent in dev environment ✉️

.github/workflows/ci.yml, apps/admin-dashboard/package.json, apps/api/package.json, apps/member-profile/package.json, package.json, packages/core/package.json, packages/email-templates/package.json, packages/types/package.json, packages/ui/package.json, packages/utils/package.json, turbo.json
Closes #74.
- Runs `yarn type-check` in the CI workflow.
- Moves `tsc --noEmit` to `type-check`.
- Adds `type-check` command to Turbo config.
=> chore: add `type-check` command 🧽

packages/core/src/infrastructure/database/scripts/setup.ts
The latest commit specifies the host (localhost) to be able to run psql using peer authentication (the default authentication method in Unix based postgresql installations)
=> fix:  add host to psql connection in `db:setup` script 🔨

apps/admin-dashboard/app/root.tsx, apps/admin-dashboard/app/shared/session.server.ts, apps/member-profile/app/root.tsx, apps/member-profile/app/shared/session.server.ts, packages/ui/src/components/toast.tsx
Closes #81.
This PR:
- Adds an `id` to the toast message.
- Passes that `id` as a React `key` to the `Toast` component.
=> fix: use react key to redisplay toast message 🍞

CONTRIBUTING.md
Updates documentation to encourage "allow edits from maintainers" to help better facilitate collaboration.
=> docs: encourage "allow edits from maintainers" option ✍️

CONTRIBUTING.md, packages/db/package.json
This PR has the same objective as what's described in #25. We had to revert that PR in #44 mainly because it broke the `CONTRIBUTION.md` onboarding steps. After further consideration, those benefits described in #25 made sense, we just had to repurpose it.
This PR:
- Adds the `postinstall` to the `db` package instead of the monorepo root. This ensures that anytime the `node_modules` within the db package changes, it'll run.
- Updates the documentation to move the `yarn` installation step after setting up environment variables, which is necessary because `kysely-codegen` is in the `postinstall` and requires the `DATABASE_URL` to be set in the environment.
=> chore(db): re-add `postinstall` script ⚡️

packages/db/src/use-cases/migrate.ts
This PR:
- Copies the original implementation of `FileMigrationProvider` from Kysely and modifies it to support Windows. I specifically needed to the `file://` prefix when building the absolute URL to a migration file.
=> fix: migrations on windows machines 🪟

apps/admin-dashboard/.env.example, apps/api/.env.example, apps/member-profile/.env.example, docker-compose.yml
This PR updates moves the exposed Redis port from it's default `6379` to `6380`. This avoids any potential clashes if the user is already running a Redis service on port `6379`.
=> fix: expose redis container on port `6380` 📦

.editorconfig
This PR adds an `.editorconfig` to resolve any inconsistencies as a result of different IDE's formatting things differently.
=> chore: add `.editorconfig` to standardize editor formatting 🫶

apps/admin-dashboard/app/entry.client.tsx, apps/member-profile/app/entry.client.tsx, apps/member-profile/app/routes/_profile.home.tsx, apps/member-profile/app/routes/_profile.profile.emails.tsx, config/eslint/base.js, packages/core/src/modules/education/queries/list-schools.ts, packages/core/src/modules/member/use-cases/update-member.ts, packages/db/src/scripts/seed.ts, packages/db/src/shared/utils.ts, packages/db/src/use-cases/migrate.ts, packages/db/src/use-cases/truncate.ts
This PR enables the [`sort-imports`](https://eslint.org/docs/latest/rules/sort-imports) rule. We ensure that it doesn't clash with [`import/order`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md) by specifying:
```js
ignoreDeclarationSort: true
```
=> chore: enable the `sort-imports` lint rule 🧼

packages/db/src/migrations/20240416173934_census_json.ts
Closes #70.
This PR updates the `json` column to be of type `json` instead of `jsonb`, which is needed because Metabase doesn't unfold `jsonb` columns.
=> feat: update census response to `json` column 📀

apps/member-profile/app/routes/_profile.home.tsx
Closes #146 
- Removes the career coaching piece from `ImportantResourcesCard` from the home page
=> fix: remove career coaching resource from home page🧋

apps/member-profile/app/routes/_profile.events.past.tsx
Closes #69 
A member can use the events panel in the Member Profile to:
- Go to the "past events" page.
- For an individual event, a member can click a "View Event Recording" button, just below the attendee list/count. This should open the link in a new tab.
=> feat: see events recordings in the member profile  👀

apps/member-profile/app/routes/_profile.events.past.tsx
This PR fixes the spacing of past events. The issue was that not all past events have event recordings, so the alignment of the different cards looked awkward.
=> fix: past events spacing 🪐

packages/core/src/modules/census/use-cases/submit-census-response.ts
When submitting a census response and selecting a company for an internship/full-time position, we're not actually saving that company if it doesn't already exist in our database. This results in us not being able to populate the name of the company when creating Metabase analytics.
=> fix: save company in census submission 💼

packages/core/package.json, packages/core/src/modules/airtable/airtable.shared.ts, packages/core/src/modules/airtable/queries/get-airtable-record.ts, packages/core/src/modules/airtable/use-cases/create-airtable-member-record.ts, packages/core/src/modules/airtable/use-cases/create-airtable-record.ts, packages/core/src/modules/airtable/use-cases/delete-airtable-record.ts, packages/core/src/modules/airtable/use-cases/update-airtable-record.ts, yarn.lock
Related to #151.
The `airtable` library is not compatible the Bun runtime so we'll need to remove it. This PR refactors the Airtable code to just use the native `fetch` API.
=> refactor: remove airtable npm library 🌭

apps/admin-dashboard/app/routes/_dashboard.events.sync-airmeet-event.tsx, apps/admin-dashboard/app/routes/_dashboard.events.tsx, apps/admin-dashboard/app/shared/constants.ts
Closes #170 
There is now an additional button under the menu button that says Sync Airmeet Event in the admin dashboard. It opens up a modal allowing the user to submit an Airmeet ID. Upon clicking submit, the Airmeet event is created in our database (and thus populated in the Member Profile) using the job function.
- Added modal to receive Airmeet ID from user.
- Calls the job function to sync airmeet event to the database.
- I have not ran an end to end simulation as I don't have an airmeet account.
- Should I add an extra type check to make sure eventID is a string?
=> feat: add an upcoming airmeet event in admin dashboard🏅

apps/member-profile/app/routes/_profile.home.claim-swag-pack._index.tsx, apps/member-profile/app/routes/companies.tsx, apps/member-profile/app/routes/integrations.oauth.github.ts, packages/core/src/infrastructure/bull/use-cases/job.ts, packages/core/src/infrastructure/bull/use-cases/register-worker.ts, packages/core/src/member-profile.server.ts, packages/core/src/modules/event/airmeet-event.service.ts, packages/core/src/modules/member/events/member-created.ts, packages/core/src/modules/member/events/member-primary-email-changed.ts, packages/core/src/modules/sentry/use-cases/report-exception.ts, packages/core/src/modules/slack/services/slack-admin.service.ts
Closes #164 
- Every instance of [`reportError`](https://github.com/colorstackorg/oyster/blob/1fe26e432ab19fffef421403402ac7ceb49150f9/packages/core/src/modules/sentry/use-cases/report-error.ts#L9) from the Sentry module has been renamed to `reportException`
=> refactor: rename `reportError` to `reportException` 🪲

CONTRIBUTING.md
Some contributors may not set up an NVM shell integration to automatically switch the node version, so this PR adds instructions on how to manually update the Node version:
```sh
nvm install && nvm use
```
This reads the `.nvmrc` file and switches the Node version specified there.
=> docs: add instructions on manually change node version #️⃣

packages/types/src/domain/application.ts
Miami Dade College does not use `.edu` emails, so we'll hardcode their email into being allowed.
=> fix: allow `mymdc.net` as email domain for applicants 📕

packages/ui/src/components/table.tsx
Closes #191 
This PR adds a right margin to the `Dropdown` element so that the positioning is consistent and not pushed off the main window. 
Before: 
After: 
Before:
After:
=> fix: dropdown formatting fix 🗄️ 

apps/admin-dashboard/app/routes/_dashboard.feature-flags.tsx, apps/member-profile/app/routes/_public.apply.tsx, packages/core/src/modules/feature-flag/feature-flag.types.ts
Closes #218.
This PR introduces a feature flag that conditionally shows the family application, and if it's disabled, shows a message about it being closed.
=> feat: add ability to close our application 🔒

apps/member-profile/app/routes/api.mixpanel.track.ts
Fix issue with parsing Mixpanel tracking request on the server. Issue occurred because we're sending json data but we were previously trying to parse as if it was a `FormData` instance.
=> fix: use `request.json` in mixpanel tracking 🟣

apps/member-profile/app/routes/_profile.resources.add.tsx, apps/member-profile/app/routes/_profile.resources.tsx, apps/member-profile/app/routes/api.resources.$id.upvote.ts, apps/member-profile/app/routes/api.resources.$id.view.ts, apps/member-profile/app/routes/api.tags.add.ts, packages/infrastructure/src/mixpanel.ts
Adds the following Mixpanel events to the new resources feature:
- `Page Viewed: Resources`
- `Resource Added`
- `Resource Link Copied`
- `Resource Tag Added`
- `Resource Upvoted`
- `Resource Viewed`
=> chore: add mixpanel tracking to resources 🟣

apps/member-profile/app/routes/_profile.resources.tsx
This fixes an issue where upon choosing a sort, we add another "orderBy" param to the query instead of resetting its value. See image below.
=> fix: reset `orderBy` query param when sorting resources 🔼

apps/admin-dashboard/app/routes/_dashboard.tsx, apps/admin-dashboard/app/routes/_profile.admins.tsx, apps/admin-dashboard/app/shared/constants.ts
Closes https://github.com/colorstackorg/oyster/issues/248
This PR Provides the following two things
1. Adds an "Admins" tab in the Admin Dashboard sidebar. (The Admins tab uses the same Icon as Students)
2. Adds a new route at /admins. For now, this is just be a blank page.
Files Created:
_profile.admins.tsx
=> feat: add an "admins" tab in the admin dashboard 👥 

apps/member-profile/app/routes/_profile.tsx, packages/ui/src/components/dashboard.tsx
Adds prefetching to the top-level navigation in the Member Profile - this is somewhat of a band aid fix to the slow queries that run in the "Points" and "Home" pages.
=> fix: add prefetching in member profile 🤞

apps/admin-dashboard/app/routes/_dashboard.admins.add.tsx, apps/admin-dashboard/app/routes/_dashboard.admins.tsx
This PR:
- Adds an `<Outlet />` in the `/admins` layout.
- Redirects the user back to the `/admins` page after adding an admin.
=> fix: add admin modal not showing in nested layout ❗️

apps/admin-dashboard/app/routes/_dashboard.students.$id.remove.tsx, packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/member/events/member-removed.ts, packages/email-templates/emails/student-removed.tsx
This PR:
- Fixes an issue with the `student-removed` email template - was getting a:
```
Error: React is not defined.
```
- Allows a checkbox input when removing a member which says whether or not to send a Code of Conduct violation email. This is important because sometimes we remove members for other reasons (ie: duplicate account).
=> feat: allow skipping of CoC violation email 🚀

apps/admin-dashboard/app/routes/_dashboard.onboarding-sessions.tsx, apps/admin-dashboard/app/routes/_dashboard.onboarding-sessions.upload.tsx, packages/core/src/modules/onboarding-session/use-cases/upload-onboarding-session.ts, packages/db/src/migrations/20240516171520_ambassador_upload.ts, packages/db/src/migrations/20240605015405_ambassador_upload.ts
Closes #214 
This PR adds a column called "Uploaded By" in the "Onboarding Sessions" table,, and displays the name of the admin who uploaded the onboarding session. It also modifies `uploadOnboardingSession` so that the adminId of the user uploading an Onboarding Session is automatically added to the database. 
If the `adminId` wasn't captured for previously uploaded Onboarding Sessions, the field is simply blank (as in the first line in the screenshot).
=> feat: onboarding session "Uploaded By" field 👋 

apps/admin-dashboard/app/routes/_dashboard.onboarding-sessions.tsx
This PR:
- Fixes an issue that shows "null null" in the Admin Dashboard when there is no admin found who uploaded an onboarding session.
- Updates the width of the "Uploaded By" column to be smaller, allowing the "Attendees" field to expand.
=> fix: don't show ambassador name if empty ❗️

apps/admin-dashboard/app/routes/_dashboard.tsx, packages/ui/src/components/dashboard.tsx
This PR sets a `max-h-screen` in the Admin Dashboard.
=> fix: set max-height for page in admin dashboard ❗️

packages/db/src/migrations/20240610221927_work_experiences_index.ts
This PR adds an index on `work_experiences.company_id`, which dramatically speeds up the `listCompanies` query.
=> fix: add index on `company_id` for speed ⚡️

apps/member-profile/app/routes/_profile.companies_.$id.tsx, apps/member-profile/app/shared/components/company-review.tsx
Closes [#318](https://github.com/colorstackorg/oyster/issues/318)
-  Add: `studentId` & `workExperiencesId` props to `<CompanyReview>` component
-  Conditionally renders 'Edit Review' feature if `studentId` EQUALS reviewerId
-  Pass `workExperiencesId` as id to render the correct `/work/:id/review/edit` modal page
-  Add: Tool tip to the 'Edit Review' feature.
-  Add: `div` wrapper to add space between header elements in `<CompanyReview>` component
Notes:
Props `studentId` & `workExperienceId` are optional b/c the `<CompanyReview>` component is used in `/recap/:date/reviews` page (I'm not sure what the this page is, but it won't need `studentId` & `workExperienceId` props, _i think??????_)
On form submission, the action function in `/work/:id/review/edit` modal redirects to a static path …
=> feat: edit review directly from companies page 🖌️ 

apps/member-profile/app/routes/_profile.home.claim-swag-pack._index.tsx
Closes #349.
This PR removes the logic that blocks Puerto Rico from being a valid state when claiming a swag pack.
=> feat: allow puerto rican addresses for swagup 🇵🇷

.github/workflows/auto-assign-author.yml, .github/workflows/auto-author-assign.yml
New Github PR [workflow](https://github.com/marketplace/actions/auto-author-assign) that auto fills the `assignees` column to the author of the PR when opened/reopened.   
**Current PR's are missing some `assignees`**
=> chore: auto assign assignees of PR's 🧑‍💼

apps/admin-dashboard/app/routes/_dashboard.resume-books.create.tsx, apps/admin-dashboard/app/routes/_dashboard.resume-books.tsx, apps/admin-dashboard/app/routes/api.companies.search.tsx, apps/member-profile/app/routes/_profile.resume-books.$id.tsx, package.json, packages/core/src/modules/resume-book/index.server.ts, packages/core/src/modules/resume-book/queries/get-resume-book.ts, packages/core/src/modules/resume-book/queries/list-resume-book-sponsors.ts, packages/core/src/modules/resume-book/queries/list-resume-books.ts, packages/core/src/modules/resume-book/resume-book.types.ts, packages/core/src/modules/resume-book/use-cases/create-resume-book.ts, packages/core/src/modules/resume-book/use-cases/submit-resume.ts, packages/db/src/migrations/20240716014614_resume_book_sponsors.ts, packages/ui/src/components/form.tsx, packages/ui/src/index.ts
=> feat: support resume book sponsors (companies) 📚

apps/member-profile/app/routes/_profile.recap.$date.resources.tsx, apps/member-profile/app/routes/_profile.resources.tsx, packages/core/src/modules/resource/queries/list-resources.ts, packages/core/src/modules/resource/use-cases/add-resource.ts, packages/db/src/migrations/20240717035628_resource_object_key.ts
This PR fixes an issue caused by introducing the `underscoreBeforeDigits` option on the database client.
=> fix: rename `s3_key` to `object_key` ❗️

apps/admin-dashboard/app/routes/_dashboard.admins.tsx, apps/admin-dashboard/app/routes/_dashboard.events.tsx, apps/admin-dashboard/app/routes/_dashboard.feature-flags.tsx, apps/admin-dashboard/app/routes/_dashboard.onboarding-sessions.tsx, apps/admin-dashboard/app/routes/_dashboard.resume-books.tsx, apps/admin-dashboard/app/routes/_dashboard.schools.tsx, apps/admin-dashboard/app/routes/_dashboard.surveys.tsx, packages/ui/src/components/table.tsx
This PR removes the usage of `size: null` for table columns and adds an empty header by default to all tables so that tables remain consistent in their spacing given the `table-fixed` styling.
=> feat: add empty header cell to all tables 🍽️

apps/member-profile/app/routes/_profile.resume-books.$id.tsx, packages/core/src/modules/resume-book/resume-book.types.ts
Fixes an issue which doesn't display an error for the LinkedIn field appropriately.
=> fix: show error message for linkedin field in resume book ❗️

apps/admin-dashboard/app/root.tsx, apps/member-profile/app/root.tsx, apps/member-profile/app/routes/_profile.profile.emails.tsx, apps/member-profile/app/routes/_public.apply._index.tsx, packages/core/package.json, packages/core/src/modules/remix.ts
This PR implements a `buildMeta` helper to make it easier to implement `meta` on a Remix page. Also tests out meta in a protected route (`/profile/emails`).
=> refactor: add `buildMeta` helper for SEO tags 🔎

packages/core/src/modules/member/use-cases/send-birthday-notification.ts
This PR is a follow up to #416 which only fetches records with a valid `slack_id`.
=> fix: add null check to birthday notification ❎

apps/member-profile/app/routes/_profile.points.tsx, apps/member-profile/app/routes/_profile.recap.$date.announcements.tsx, apps/member-profile/app/shared/components/slack-message.tsx
This PR fixes an issue which doesn't parse the raw Slack message text in the activity history.
=> fix: parse slack message in activity history 👖

apps/member-profile/app/routes/_profile.resume.review.tsx, packages/core/src/modules/resume/resume.core.ts, packages/core/src/shared/utils/file.utils.ts, packages/core/src/shared/utils/zod.utils.ts
Closes #448 and #449.
This PR:
- Implements the `getTextFromPDF` function which parses the PDF into a string.
- In the `reviewResume` function, we're now passing in the parsed text of a resume, instead of an image of the resume like we were doing before. This is the huge gain because we no longer have to rely on the AI's image parsing abilities, it just parses text which is much more certain and simple.
- Updated the prompt to include leadership experiences.
- Adds validation to the `action` in the review resume page, ensuring that only files are being uploaded (not sure how some people may have gotten around that).
=> fix: improve parsing to avoid hallucinations in resume review ❗️

packages/core/src/modules/resource/queries/list-resources.ts
Closes #464
- the search term will now check the title and the description of the resources
- screenshot below shows the feature working properly
=> feat: improve resource search to include description 🔎

.husky/pre-commit, package.json, yarn.lock
This PR removes `husky` and `lint-staged` from the codebase. They're a great idea in theory, but can hurt DX with slow commit times. At the end of the day, our CI pipeline will do all the necessary work to ensure our formatting is proper. We'll let the computers in the sky do the work instead of our local machines.
=> chore: remove `husky` + `lint-staged` 🪓

apps/api/src/routers/slack-event.router.ts, apps/api/src/routers/slack-event.types.ts, packages/core/src/modules/ai/ai.ts, packages/core/src/modules/slack/slack.ts, packages/db/src/index.ts, packages/db/src/use-cases/create-database-connection.ts
This PR:
- Doesn't emit the `slack.chatbot.message` if the DM is from a bot (ie: `ColorStack` app).
- Logs the Anthropic token usage after a chat completion.
- Updates the `createDatabaseConnection` to accept an optional database URL as an argument.
- Improves the UX of the AI chatbot:
- First checks whether or not the input is a question and if it's not, says "can't answer this".
- Then, immediately sends a "Searching our Slack history..." message.
- Updates the linked thread presentation (uses the **`[1]`** as an example).
- Uses the top 5 most similar messages in the Pinecone query.
- The prompt now takes into account the creation date + score of the match.
- Additionally, the max tokens is `1000`.
=> feat: improve ai chatbot prompt + ux 📈

apps/api/src/routers/slack.router.ts, packages/core/src/modules/slack/slack.ts
This PR fixes an issue with the "Ask ColorStack AI" functionality for top-level messages.
=> fix: handle case where `thread_ts` is not present in shortcut ❗️

packages/core/src/modules/slack/slack.ts
This PR updates the way we respond to a public thread/question. Instead of sending a full LLM response, we'll instead just link similar threads. The pros of this include:
- The response is shorter and less overwhelming.
- This will remind our users to search before asking a question.
This PR also:
- Includes a footnote that links members back to our app's DM which should push them to ask questions to the chatbot.
- Excludes the current thread from being linked.
=> feat: update ai answer for public question 🔼

packages/core/src/modules/slack/slack.ts
This PR:
- Increases the threshold of a match to `>= 0.98`, ensuring that it will only include a match if it is highly confident about it. Naturally, this means that certain responses that may actually be great but are scored lower will be left out. The thought process here is "a correct/excluded answer is better than a wrong/included one".
- Updates the formatting of the reply to use bullet points and removes long message (albeit not _real_ bullet points).
- Fixes an issue that included threads without replies in the reranking.
=> feat: increase threshold + formatting of bot reply to thread 🧵

packages/core/src/modules/slack/slack.ts
This PR fixes a bug that wrongly indexes the reranked documents that get returned from the Cohere API.
=> fix: buggy indexing of array for reranking 🐞

packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/notification/notification.worker.ts, packages/core/src/modules/notification/use-cases/send-ephemeral-slack-notification.ts, packages/core/src/modules/notification/use-cases/send-slack-notification.ts, packages/core/src/modules/slack/slack.ts, packages/db/src/migrations/20240916211925_slack_message_auto_reply.ts
This PR:
- Supports ephemeral Slack notification using the `chat.postEphemeral` method on the Slack API, which requires a user ID since only they'll be able to see the message.
- Adds a corresponding `notification.slack.ephemeral.send` Bull job.
- Updates the auto responses to a public thread with ephemeral messages in the case that an error occurred or there was no relevant threads found.
- Adds a `auto_replied_at` column on the `slack_messages` table so that we can track if/when a message was auto-replied to.
=> feat: support ephemeral slack notifications + better ai replying 🤖

packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/mixpanel.ts, packages/core/src/modules/notification/use-cases/send-slack-notification.ts, packages/core/src/modules/slack/slack.ts, packages/core/src/modules/slack/slack.worker.ts, packages/core/src/modules/slack/use-cases/add-slack-message.ts
Adds support for auto replying to questions asked in certain public channels. These responses are full LLM (RAG implementation) responses but are sent to DM. The key UX decision here is we don't want to take away from the community feel by having the bot reply publicly to every single message in a channel (despite that others may learn from it).
This PR:
- Implements the core `answerPublicQuestionInPrivate` function, which is similar to `answerChatbotQuestion` with a slightly different UX (ie: won't respond if nothing high confidence is found).
- Adds a `slack.question.answer.private` Bull job.
- Stores the "auto reply channels" in Redis, and reads that after a message is created in order to determine
- Adds a `Public Question Answered` Mixpanel event.
- Makes the `user` optional on a …
=> feat: auto reply to public questions via dm 🤖

packages/core/src/modules/slack/slack.ts
This PR makes a couple minor UX improvements to the messaging of the chatbot responses.
=> feat: improve ux of deep linked app dm 💬

packages/core/src/modules/slack/slack.ts
Small follow-up PR to use `user_id` from Slack API response.
=> refactor: use `user_id` from `slack.auth.test` 🔒

packages/core/src/modules/member/member.worker.ts
This PR fixes an issue with the `updatePointTotals` SQL query where we divide by zero. We now use the `greatest` function in SQL to fallback to 1.
=> fix: "division by zero" issue in updating points per day 🏆

apps/member-profile/app/shared/queries/index.ts, packages/core/src/modules/education/use-cases/check-most-recent-education.ts, packages/core/src/modules/resume/resume.core.ts
This PR fixes a bug in which the education history was sorted by `start_date` then `end_date`, when it should've been the other way around.
=> fix: order education history by end date first 🔽

CONTRIBUTORS.yml, docker-compose.yml
- Added my name to the `contributors.yml` file
- Removes the 'version' property in the `docker-compose.yml` file. This property is now officially [considered obsolete](https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313).
Currently this warning message appears on `yarn dx:up`
```
\docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
```
=> chore: remove `version` from docker compose 🐋

packages/core/src/modules/application/application.core.ts
This PR rejects any applications in which the email has been used in a past application that was accepted. This is relevant for when we remove members who try to apply to ColorStack again.
=> fix: reject applicants who were already accepted in the past ❗️

docs/how-to-enable-integrations.md, packages/core/src/modules/pinecone.ts
Closes #567 
#505 
- Makes Pinecone API configuration optional in local development
- Adds a console warning message
=> fix: make pinecone api key optional in dev ❗️

apps/admin-dashboard/app/routes/_dashboard.applications.tsx, apps/admin-dashboard/app/routes/_dashboard.bull.$queue.tsx, apps/admin-dashboard/app/routes/_dashboard.events.tsx, apps/admin-dashboard/app/routes/_dashboard.feature-flags.tsx, apps/admin-dashboard/app/routes/_dashboard.gamification.activities.tsx, apps/admin-dashboard/app/routes/_dashboard.onboarding-sessions.tsx, apps/admin-dashboard/app/routes/_dashboard.resume-books.tsx, apps/admin-dashboard/app/routes/_dashboard.schools.tsx, apps/admin-dashboard/app/routes/_dashboard.students.tsx, apps/admin-dashboard/app/routes/_dashboard.surveys.tsx, packages/core/src/modules/admin/admin.ui.tsx, packages/ui/src/components/table.tsx
This PR refactors the `Table` component such that:
- There is no longer a `Dropdown` prop.
- Instead, we can just pass this into the `columns` prop, since it's just a column at the end of the day.
- We'll add the `sticky` field which will mimic the same functionality.
This is preparation for showing our opportunities in which you'll be able to bookmark within the row itself.
=> refactor: generalize table sticky column 🔀

apps/admin-dashboard/app/routes/_dashboard.bull.$queue.jobs.$id.tsx, packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/employment/use-cases/send-company-review-notifications.ts, packages/core/src/modules/member/member.worker.ts, packages/db/src/migrations/20241029041628_company_review_notification.ts
Follow up to #556, which makes the company review notification idempotent by marking each work experience's `reviewNotificationSentAt` column after sending a notification. This ensures we never send duplicates.
This PR also supports a `before`/`after` timestamp for the notification job, which will make it easier for us to backfill notifications for all work experiences that ended this summer, not just this last month.
=> feat: make company review notification idempotent 1️⃣

packages/core/src/shared/utils/browser.utils.ts
This PR fixes an edge case that doesn't properly read some URLs related to opportunities. We separate the waiting of the network being idle.
=> fix: separate wait for network idle in puppeteer ⏰

apps/admin-dashboard/railway.json, packages/db/src/use-cases/create-database-connection.ts
Update the database connection string to use the `DATABASE_PUBLIC_URL` during the Railway build phase, since we updated the environment variable to use the private network URL at runtime.
=> chore: try private networking for database in admin dashboard 🔒

packages/db/src/migrations/20241112182800_job_offers.ts
Accidentally removed the `benefits` column from the `full_time_job_offers` table.
=> fix: add missing `benefits` column in job offers migration ❗️

packages/db/src/migrations/20241116190627_opportunities_unique.ts
This PR fixes an issue that sometimes duplicates an opportunity from a failed Bull job by adding a unique constraint on `(slack_channel_id, slack_message_id)`.
=> fix: add unique constraint to opportunity's slack message 👖

packages/core/src/modules/compensation/job-offers.ts
This PR fixes an issue where the sign on bonus isn't persisting for internship offers. This also updates the backfill query to only find messages with certain keywords.
=> fix: sign-on bonus for internship offers ❗️

apps/api/src/routers/slack.router.ts, packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/slack/use-cases/add-slack-message.ts
This PR fixes an issue that is creating a duplicate offer when the bot notification comes in.
=> fix: skip offer message when posted by bot ❗️

apps/api/src/routers/slack.router.ts, apps/api/src/routers/slack.types.ts, packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/slack/use-cases/add-slack-message.ts
This PR is a follow up to #597 that checks if a file was shared or not. Sometimes members will share a file in the following (or previous) message, they will ask for a review. We don't want to send multiple notifications in that case.
=> fix: don't send resume review nudge unless file was shared 🗂️

apps/api/src/routers/slack.router.ts, packages/core/src/infrastructure/bull/bull.types.ts, packages/core/src/modules/slack/events/slack-reaction-added.ts, packages/core/src/modules/slack/slack.ts, packages/core/src/modules/slack/slack.worker.ts
Used `slack.reaction.add` to add a Slack reaction to the original message query that the ColorStack bot responds to once it provides an answer. Also, thanks to my Bloomberg mentor Pallav, was able to get some insight on how it may be possible to delete the loading message the bot sends once it provides an answer. Will include in the comments of this PR.
Closes #538
- Create a new job to add the ColorStack logo as a reaction to the Slack message the bot is responding to
=> feat: implement ai chatbot reaction response 🤖 

apps/member-profile/app/routes/_profile.resources.add.tsx, apps/member-profile/app/shared/components/resource-form.tsx, packages/db/src/migrations/20241027040259_abdulmajeed.ts
Closes #269
This PR adds a checkbox field above the "Title" field in the form for adding resources.
=> feat: add confirmation that user has searched for duplicate resources ✅ 

apps/member-profile/app/shared/components/ethnicity-combobox.tsx
Closes #468 
This PR updates the components that are in charge of rendering the ethnicities dropdown. Specifically these components where updated to:
* render a list of countries that does not spill over past the height of the window screen. 
* dynamically update the dropdown size and number of countries the component/dropdown renders to consistently have 30 px between the bottom of the window screen and the bottom of the ethnicities dropdown.
This update was tested on both Chrome and Safari as seen in screenshots below.
=> fix: update ethnicities dropdown ⛳️

packages/core/src/modules/slack/use-cases/add-slack-message.ts
This PR:
- Sends a notification to the `#feed` channel when a thread hits 100 replies.
- Updates the internal notification when a thread hits 500 replies.
=> feat: notify feed channel when thread hits 100 replies 💬

apps/admin-dashboard/app/routes/_dashboard.feature-flags.tsx, apps/admin-dashboard/app/routes/_dashboard.onboarding-sessions.tsx, apps/member-profile/app/routes/_profile.companies.tsx, apps/member-profile/app/routes/_profile.companies_.$id.tsx, apps/member-profile/app/routes/_profile.directory.join._index.tsx, apps/member-profile/app/routes/_profile.directory.join.finish.tsx, apps/member-profile/app/routes/_profile.directory.join.tsx, apps/member-profile/app/routes/_profile.directory_.$id.tsx, apps/member-profile/app/routes/_profile.events.past.tsx, apps/member-profile/app/routes/_profile.events.upcoming.$id.register.tsx, apps/member-profile/app/routes/_profile.events.upcoming.tsx, apps/member-profile/app/routes/_profile.home.tsx, apps/member-profile/app/routes/_profile.offers.full-time.$id_.edit.tsx, apps/member-profile/app/routes/_profile.offers.internships.$id_.edit.tsx, apps/member-profile/app/routes/_profile.opportunities.$id_.edit.tsx, apps/member-profile/app/routes/_profile.opportunities.tsx, apps/member-profile/app/routes/_profile.points.tsx, apps/member-profile/app/routes/_profile.profile.referrals.tsx, apps/member-profile/app/routes/_profile.resources.$id_.edit.tsx, apps/member-profile/app/routes/_profile.resources.tsx, apps/member-profile/app/shared/components/offer.tsx, apps/member-profile/app/shared/components/slack-message.tsx, packages/ui/package.json, packages/ui/src/components/button.tsx, packages/ui/src/index.ts, packages/ui/src/utils/cx.ts, yarn.lock
This PR creates a `Button.Slot` component which uses Radix's utility `Slot` component to merge props onto the child. This means that we can be more declarative when trying to apply button styling to an anchor element.
=> refactor: use `Slot` component instead of `getButtonCn` 🔄

packages/core/src/modules/slack/use-cases/add-slack-message.ts
This PR fixes a small bug that uses the ID of the reply for the "busy thread notification" instead of the ID of the thread.
=> fix: use thread id for busy thread notification ❗️

packages/core/src/modules/opportunities.ts
This PR adds `docs.google.com` to the no-list for reading the opportunity's site content w/ puppeteer.
=> fix: don't process google form posting as opportunities ❗️

packages/core/src/modules/opportunities.ts, packages/core/src/modules/slack/use-cases/change-slack-message.ts
=> fix: delete opportunity when slack message is soft-deleted ❗️

packages/core/src/modules/employment/queries/list-companies.ts, packages/core/src/modules/slack/use-cases/add-slack-message.ts
Closes CS-194.
Converts the `listCompanies` query to use joins instead of subqueries.
=> fix: slow companies query ❗️

packages/core/src/modules/events/events.ts
Already made progress on the performance of this query, taking one more speed jump.
=> fix: speed up the `listPastEvents` query ⚡️

packages/core/src/modules/opportunities.ts
This PR potentially fixes an LLM hallucination issue when refining an opportunity with AI.
=> fix: potential ai hallucination with opportunity refinement ❗️

apps/member-profile/app/routes/_profile.opportunities.tsx, apps/member-profile/app/routes/_profile.tsx, packages/core/src/modules/opportunities.ts
This PR removes the status filter on opportunities. Most people only want to see open opportunities and don't care for expired opportunities. This also sets the default expiration to 1 month.
=> chore: remove opportunity status filter 🧼

apps/admin-dashboard/app/routes/_dashboard.schools.$id.chapter.create.tsx, apps/admin-dashboard/app/routes/_dashboard.schools.tsx, apps/admin-dashboard/app/shared/constants.ts, packages/core/package.json, packages/core/src/modules/chapters/chapters.ts, packages/db/src/migrations/20240904030122_chapters.ts, packages/db/src/migrations/20250225190635_chapters.ts
Closes #498
A chapters table is created, so that admins can mark a school that has a chapter. 
- Should store schools that have chapters by linking school_id and storing timestamp when school was added to `chapters` table
- New dropdown with a confirmation modal to add a school to chapters table (should not be shown for schools already in table)
-  [x] Add new dropdown field to school to add as a chapter in admin dashboard
https://github.com/user-attachments/assets/8c5afe92-80ab-4d0c-82fa-dce0c9015711
=> feat: infrastructure for school chapters 📖 

apps/member-profile/app/routes/_profile.opportunities.$id.tsx, apps/member-profile/app/routes/_profile.opportunities.tsx, apps/member-profile/app/shared/components/index.tsx
The opportunities board has a lot of unrefined opportunities because we are unable to parse the website and nobody has manually helped with that. In order to prevent this "empty" look, we'll just not show any opportunities that we can't refine.
This PR also fixes 2 bugs:
- The linking of the opportunity to a Slack message.
- The aspect ratio of the company logo when there is a large title.
=> fix: don't show unrefined (empty) opportunities 🫣

packages/core/src/infrastructure/bull.types.ts, packages/core/src/modules/opportunities.ts
This PR implements the ability to check for opportunities that have expired. It does this by navigating to the opportunity's website and searching for keywords/phrases such as `filled`, `no longer open`, etc.
=> feat: job to check for expired opportunities ❎

apps/member-profile/app/routes/_profile.opportunities.$id.tsx, packages/core/src/infrastructure/bull.types.ts, packages/core/src/modules/opportunities.ts, packages/db/src/migrations/20250226180740_opportunity_expiration_check.ts
This PR updates the way we do expiration checks by looking at the `last_expiration_check` field. This also separates the expiration job into 2 (one for an individual check and one for querying all opportunities). The latter now just emits an individual job instead of running the logic in its own job.
=> feat: add `last_expiration_check` field to opportunities 🚀

packages/core/src/infrastructure/puppeteer.ts
This PR _potentially_ fixes an issue with bot detection when reading a webpage's content using puppeteer. Not sure if this will work in production since our IP address might have been blacklisted.
=> fix: attempt to escape bot detection on workday 🤖

packages/ui/src/components/filter.tsx
This PR fixes a bug which doesn't scroll the filter item into view when using the keyboard.
=> fix: scroll filter item into view when using keyboard 🎹

packages/ui/src/components/filter.tsx
This PR fixes a bug in which the scroll resets when clicking on an item within a scrolled view where the `FilterRoot` component is mounted in the same page. The issue was the `useClickOutside` hook that ran within the `FilterRoot` component.
=> fix: scroll bug related to the filter component ❗️

packages/core/package.json, packages/core/src/infrastructure/puppeteer.ts, yarn.lock
This PR will help reduce costs for web scraping by using a set of dedicated proxies instead of a browser instance that various SaaS companies offer. Now that we have a dedicated set of proxies, we need to use them with `puppeteer`.
The key here is we need to tell puppeteer we are using a proxy server, then we need to authenticate with it, ie:
```ts
const context = await browser.createBrowserContext({ proxyServer: proxy });
const page = await context.newPage();
await page.authenticate({
password: OXYLABS_PASSWORD,
username: OXYLABS_USERNAME,
});
```
This PR:
- Introduces the `OXYLABS_USERNAME`, `OXYLABS_PASSWORD`, and `OXYLABS_PROXIES` environment variables.
- Removes the `DEFAULT_TIMEOUT` on the puppeteer settings (already defaults to 30 seconds).
- Uses the `user-agents` package for more …
=> feat: use manual proxy rotation for web scraping 🔁

apps/admin-dashboard/app/routes/_dashboard.applications.tsx, apps/admin-dashboard/app/routes/_dashboard.events.tsx, apps/admin-dashboard/app/routes/_dashboard.feature-flags.tsx, apps/admin-dashboard/app/routes/_dashboard.gamification.activities.tsx, apps/admin-dashboard/app/routes/_dashboard.onboarding-sessions.tsx, apps/admin-dashboard/app/routes/_dashboard.resume-books.tsx, apps/admin-dashboard/app/routes/_dashboard.schools.$id.chapter.create.tsx, apps/admin-dashboard/app/routes/_dashboard.schools.$id.edit.tsx, apps/admin-dashboard/app/routes/_dashboard.schools.create.tsx, apps/admin-dashboard/app/routes/_dashboard.schools.tsx, apps/admin-dashboard/app/routes/_dashboard.students.tsx, packages/core/src/modules/admins/admins.ui.tsx
This PR fixes a bug when editing schools which didn't preserve search params and preset scroll.
=> fix: preserve search params when editing schools ❗️

packages/db/package.json, packages/db/src/use-cases/migrate.ts, yarn.lock
Closes #770.
This PR fixes the flakiness around Windows machines and the Kysely `FileMigrationProvider`. It seems to be working in most cases but not all. We use the most recent Kysely [recommended solution](https://github.com/kysely-org/kysely/issues/768#issuecomment-2118886520) to use the [`pathe`](https://www.npmjs.com/package/pathe) package, which normalizes all operations to use a `/` instead of `\`.
=> fix: use `pathe` for kysely file migration provider ❗️

packages/ui/src/components/table.tsx
This PR fixes an issue when using the `Table.Dropdown` component, which fails to open a modal due to the `Portal` that we're using. This was introduced in #773.
=> fix: dropdown portal bug ❗️

apps/member-profile/app/routes/_profile.peer-help.tsx, apps/member-profile/app/shared/components/peer-help.tsx
This PR fixes a small issue where the white space of a help request description was not being preserved.
=> fix: preserve white space for help request description ❗️

apps/member-profile/app/routes/_profile.peer-help.tsx
This PR fixes a small scroll issue in the Peer Help page.
=> fix: prevent scroll reset in peer help ❗️

packages/core/src/modules/events/events.ts, packages/core/src/modules/peer-help.ts, packages/core/src/modules/slack/use-cases/create-slack-channel.ts, packages/core/src/modules/slack/use-cases/send-emoji-update.ts
This PR:
- Sends a `#feed` channel notification when a help request is posted.
- Sends a `#feed` channel notification when a new Airmeet event is created and open for registration.
- Moves the Slack emoji notification to a different channel.
=> feat: add feed notification for peer help/event 🚀

apps/member-profile/app/routes/_profile.opportunities.tsx, apps/member-profile/app/routes/_profile.resources.$id_.edit.tsx, apps/member-profile/app/routes/_profile.resources.tsx, apps/member-profile/app/routes/api.tags.add.ts, apps/member-profile/app/routes/api.tags.search.ts, apps/member-profile/app/shared/components/resource-form.tsx, apps/member-profile/app/shared/components/resource.tsx, packages/core/src/modules/resources/queries/list-resources.ts, packages/core/src/modules/resources/queries/list-tags.ts, packages/core/src/modules/resources/resources.types.ts, packages/core/src/modules/resources/shared/index.ts, packages/core/src/modules/resources/use-cases/add-resource.ts, packages/core/src/modules/resources/use-cases/create-tag.ts, packages/core/src/modules/resources/use-cases/update-resource.ts, packages/db/src/migrations/20250514204059_resource_tags.ts, packages/db/src/scripts/seed.ts
This PR:
- Renames the `resource_tags` table to `resource_tag_associations`.
- Renames the `tags` table to `resource_tags`.
- Supports a `color` field on `resource_tags` table.
- Retroactively stores a `color` field on each resource tag.
- Updates all components and queries related to showing the color.
=> feat: support color for resource tags 🏷️

packages/core/src/infrastructure/mixpanel.ts, packages/core/src/modules/linkedin.ts, packages/db/src/migrations/20250611203613_linkedin_sync.ts
This PR adds a `linkedin_synced_at` column to the `students` table in order to track the timestamp for when a LinkedIn is synced to a member's profile. Also updates this in the `syncLinkedInProfile` method.
=> feat: track timestamp for linkedin sync 🔀

apps/member-profile/app/routes/_profile.companies.tsx, apps/member-profile/app/routes/_profile.companies_.$id.employees.tsx, apps/member-profile/app/routes/_profile.companies_.$id.tsx, packages/core/src/modules/employment/queries/list-company-employees.ts, packages/core/src/modules/employment/ui/work-experience.tsx, packages/ui/src/components/search-bar.tsx
This PR:
- Updates the `listCompanyEmployees` to accept a `search` parameter. It also does some extra calculation in the query which sums up the total time someone has spent at the company, then sorts in descending order based off of that.
- Updates the UI of the company employees page:
- Shows one big list of employees instead of separating current/past.
- Shows a `Current` | `Past` pill for the employee.
- Shows the time spent at the company.
- Fixes other visual bugs.
=> feat: make company employees searchable 🔎

packages/core/src/infrastructure/bull.ts, packages/core/src/modules/linkedin.ts
This PR:
- Splits LinkedIn batches into separate jobs if there are more than 100 members.
- Updates the default Bull removal logic to keep 10x the number of completed/failed jobs.
=> feat: split linkedin batches into jobs 🖖

.github/workflows/ci.yml, package.json
This PR makes the minimum node version `22.17.0` in order to support installing vite 7.
=> fix: bump minimum node version to `22.17.0` to support vite 7 ❗️

turbo.json
This PR allows the Sentry environment variables to be passed through in the `build` command.
=> fix: allow sentry variables in `build` via turbo ❗️

bun.lock, packages/core/package.json, packages/core/src/modules/authentication/oauth.service.ts, packages/core/src/modules/authentication/services/google-oauth.service.ts
This PR reimplements the Google OAuth 2.0 integration using native `fetch` instead of using the huge `googleapis` SDK.
=> refactor: remove `googleapis` in favor of native `fetch` 🔄

packages/core/src/modules/applications/applications.ts, packages/core/src/modules/applications/applications.types.ts, packages/types/src/domain/student.ts, packages/utils/src/index.ts
This PR:
- Automatically rejects an applicant if they are using a `linked_in_url` that is already found in the `members` table.
- Updates the Zod schema for `linkedInUrl` such that it removes the `www.` from the value. This is so that we can get a better gauge for uniqueness.
=> feat: reject applicant if linkedin url already found ❎

apps/api/src/handlers/oauth.ts, packages/utils/src/index.ts
This PR fixes an issue with the cookie that gets set after LinkedIn authentication...need to set the `Domain` attribute which we calculate from the URL `hostname`.
=> fix: set domain for linkedin oauth redirection 🔒

apps/member-profile/app/routes/_profile.tsx, packages/ui/src/components/input.tsx, packages/ui/src/components/select.tsx
This PR reverts the changes to `getInputCn` with regards to readonly styling.
=> refactor: remove readonly styling for input 🔄

packages/core/src/modules/applications/applications.ts
This PR rejects applicants that use a LinkedIn that not only a current member has but that a past accepted application had.
=> feat: check past accepted applications linkedin 🔒

apps/member-profile/app/routes/_profile.profile.education.sync.tsx, apps/member-profile/app/routes/_profile.profile.work.sync.tsx, packages/core/src/modules/linkedin.ts
This PR updates the caching logic for fetching a LinkedIn profile. When triggered from the Member Profile, we'll always use fresh data, which is better for the user experience when they update something on their LinkedIn and want to see that immediately reflected.
=> fix: don't use cached results for linkedin when triggered from mp 🧹

apps/admin-dashboard/app/routes/_dashboard.admins.tsx, packages/core/src/modules/admins/admins.ts
This PR allows past ambassadors to be added as admins after they have already been archived.
=> feat: allow re-adding ambassador as admin ➕

apps/admin-dashboard/app/routes/_dashboard.students.remove.tsx
This PR allows small batches to fail but still allows the other batches to go through.
=> fix: fail more elegantly for large member removal batches 💃🏽

apps/admin-dashboard/app/routes/_dashboard.students.remove.tsx, packages/core/src/infrastructure/bull.types.ts, packages/core/src/modules/members/members.worker.ts, packages/core/src/modules/members/use-cases/batch-remove-members.ts
This PR moves the batch member deletion to run completely asynchronously since it can take 30+ minutes to complete for a long list.
=> fix: run batch member delete asynchronously ⏰
